/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jmg.buzios.view.comercio;

import com.jmg.buzios.controller.comercio.RecogerRecursodeMercado;
import com.jmg.buzios.controller.edificio.ConstruirEdificio;
import com.jmg.buzios.model.ciudad.Ciudad;
import com.jmg.buzios.model.isla.Recurso;
import com.jmg.buzios.view.ciudad.VCiudad;
import com.jmg.buzios.view.edificios.VVerMercado;

import javax.swing.*;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * @author Alumno
 */
public class VRecorgerRecursoMercado extends javax.swing.JFrame {

    private VCiudad vciudad;
    private VVerMercado vermercadito;
    private Recurso recurso;
    private Integer cantidad;
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cboCiudadAlmacenamiento;
    private javax.swing.JButton cmdRecogerRecurso;
    private java.awt.Label label1;
    private javax.swing.JLabel lblCantidadtotal;
    private javax.swing.JLabel lblCiudadelegida;
    private javax.swing.JLabel lblCiudadelegida1;
    private javax.swing.JLabel lblRecursoaRecoger;
    private javax.swing.JLabel lblRecursoaRecoger1;
    private javax.swing.JLabel lblRecursoelegido;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private javax.swing.JTextField txtCantidadaRecojer;
    public VRecorgerRecursoMercado(VVerMercado vermercadito, VCiudad vciudad, Recurso recurso, Integer cantidad) {
        initComponents();
        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/back-3.png"))); // NOI18N

        this.vciudad = vciudad;
        this.recurso = recurso;
        this.cantidad = cantidad;
        this.vermercadito = vermercadito;
        this.setLocationRelativeTo(null);
        this.show();
        for (int i = 0; i < this.vciudad.getCiudad().getJugador().getCiudades().size(); i++) {
            this.cboCiudadAlmacenamiento.addItem(this.vciudad.getCiudad().getJugador().getCiudades().get(i).getNombre());
        }
        this.lblRecursoelegido.setText(this.recurso.getNombrerecurso());
        this.lblCantidadtotal.setText(this.cantidad + "");


        this.show();
        this.repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        lblRecursoaRecoger = new javax.swing.JLabel();
        lblCiudadelegida = new javax.swing.JLabel();
        lblCiudadelegida1 = new javax.swing.JLabel();
        lblRecursoaRecoger1 = new javax.swing.JLabel();
        txtCantidadaRecojer = new javax.swing.JTextField();
        lblRecursoelegido = new javax.swing.JLabel();
        lblCantidadtotal = new javax.swing.JLabel();
        cmdRecogerRecurso = new javax.swing.JButton();
        cboCiudadAlmacenamiento = new javax.swing.JComboBox();

        label1.setText("label1");

        lblRecursoaRecoger.setText("Recurso a Recoger");

        lblCiudadelegida.setText("Ciudad de Almacenamiento");

        lblCiudadelegida1.setText("Cantidad a Recoger");

        lblRecursoaRecoger1.setText("Cantidad en Mercado");

        txtCantidadaRecojer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCantidadaRecojerKeyReleased(evt);
            }
        });

        lblRecursoelegido.setText("Madera");

        lblCantidadtotal.setText("0");

        cmdRecogerRecurso.setText("Recoger Recurso");
        cmdRecogerRecurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRecogerRecursoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
                panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelImage1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelImage1Layout.createSequentialGroup()
                                                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(lblCiudadelegida1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(lblRecursoaRecoger1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lblCantidadtotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(txtCantidadaRecojer))
                                                .addGap(20, 20, 20))
                                        .addGroup(panelImage1Layout.createSequentialGroup()
                                                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(lblCiudadelegida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(lblRecursoaRecoger, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(cboCiudadAlmacenamiento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(lblRecursoelegido, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
                                                .addGap(0, 18, Short.MAX_VALUE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImage1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmdRecogerRecurso)
                                .addGap(65, 65, 65))
        );
        panelImage1Layout.setVerticalGroup(
                panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelImage1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblRecursoaRecoger)
                                        .addComponent(lblRecursoelegido))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblCiudadelegida)
                                        .addComponent(cboCiudadAlmacenamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(7, 7, 7)
                                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblRecursoaRecoger1)
                                        .addComponent(lblCantidadtotal))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblCiudadelegida1)
                                        .addComponent(txtCantidadaRecojer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmdRecogerRecurso)
                                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(panelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCantidadaRecojerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadaRecojerKeyReleased
        try {
            if (Integer.parseInt(this.txtCantidadaRecojer.getText()) <= 0) {

                this.txtCantidadaRecojer.setText("");
            } else {
                if (Integer.parseInt(this.txtCantidadaRecojer.getText()) > Integer.parseInt(this.lblCantidadtotal.getText())) {
                    this.txtCantidadaRecojer.setText(this.lblCantidadtotal.getText());
                }
            }
        } catch (NumberFormatException e) {
            this.txtCantidadaRecojer.setText("");
            this.repaint();
        }
    }//GEN-LAST:event_txtCantidadaRecojerKeyReleased

    private void cmdRecogerRecursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRecogerRecursoActionPerformed
        if (!"".equals(this.txtCantidadaRecojer.getText())) {
            try {
                RecogerRecursodeMercado recoger;
                recoger = new RecogerRecursodeMercado(this.vciudad, buscar_ciudad_jugador(), new Recurso(this.lblRecursoelegido.getText()), Integer.parseInt(this.txtCantidadaRecojer.getText()));
                recoger.CURecogerRecursodeMercado();
                if (buscar_ciudad_jugador().getNombre().equals(this.vciudad.getCiudad().getNombre())) {
                    ConstruirEdificio.actualizarinterfazgrafica(vciudad);
                }

                this.vermercadito.hide();
                this.hide();
            } catch (SQLException ex) {
                Logger.getLogger(VRecorgerRecursoMercado.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(panelImage1, "Debe ingresar que cantidad desea recoger");
        }
    }//GEN-LAST:event_cmdRecogerRecursoActionPerformed

    private Ciudad buscar_ciudad_jugador() {
        Ciudad ciudadjugador = new Ciudad();
        ciudadjugador.setNombre((String) this.cboCiudadAlmacenamiento.getSelectedItem());
        ciudadjugador.setJugador(this.vciudad.getCiudad().getJugador());
        return ciudadjugador;
    }
    // End of variables declaration//GEN-END:variables
}
