/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jmg.buzios.view.comercio;

import com.jmg.buzios.controller.comercio.ComprarRecursosaJuego;
import com.jmg.buzios.controller.comercio.ComprarRecursosdeJugador;
import com.jmg.buzios.controller.comercio.VerOferta;
import com.jmg.buzios.model.comercio.Oferta;
import com.jmg.buzios.model.comercio.OfertaJugador;
import com.jmg.buzios.view.ciudad.VCiudad;
import com.jmg.buzios.view.edificios.VVerMercado;
import org.edisoncor.gui.panel.PanelImage;

import javax.swing.*;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * @author Alumno
 */
public class VVerOferta extends javax.swing.JFrame {

    private List<Oferta> ofertas;
    private VCiudad vciudad;

    private Oferta ofertaelegida;
    private VVerMercado vermercado;
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cboFiltro;
    private javax.swing.JButton cmcComprarOferta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCantidadOfertada;
    private javax.swing.JLabel lblJugadorOferente;
    private javax.swing.JLabel lblNumeroOferta;
    private javax.swing.JLabel lblRecursoBuscado;
    private javax.swing.JLabel lblRecursoavender;
    private javax.swing.JList lstOfertas;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private org.edisoncor.gui.panel.PanelImage pantallaDetalleOferta;
    private javax.swing.JTextField txtCantidadacomprar;
    public VVerOferta(VCiudad vciudad, VVerMercado vermercado) {

        initComponents();

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/back-3.png"))); // NOI18N
        pantallaDetalleOferta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/backg-1.png"))); // NOI18N

        this.vermercado = vermercado;
        this.vciudad = vciudad;
        this.getPantallaDetalleOferta().setVisible(false);
        this.setLocationRelativeTo(null);
        this.show();
    }

    public JLabel getLblRecursoBuscado() {
        return lblRecursoBuscado;
    }

    public PanelImage getPantallaDetalleOferta() {
        return pantallaDetalleOferta;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        pantallaDetalleOferta = new org.edisoncor.gui.panel.PanelImage();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblNumeroOferta = new javax.swing.JLabel();
        lblRecursoavender = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblCantidadOfertada = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblJugadorOferente = new javax.swing.JLabel();
        cmcComprarOferta = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblRecursoBuscado = new javax.swing.JLabel();
        txtCantidadacomprar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstOfertas = new javax.swing.JList();
        cboFiltro = new javax.swing.JComboBox();

        panelImage1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pantallaDetalleOferta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Recurso Ofertado");

        jLabel2.setText("Oferta N°");

        lblNumeroOferta.setText("0");

        lblRecursoavender.setText("Madera");

        jLabel5.setText("Cantidad Ofertada");

        lblCantidadOfertada.setText("000");

        jLabel7.setText("Jugador Oferente");

        lblJugadorOferente.setText("nn");

        cmcComprarOferta.setText("Comprar Oferta");
        cmcComprarOferta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmcComprarOfertaActionPerformed(evt);
            }
        });

        jLabel3.setText("Recurso Buscado");

        lblRecursoBuscado.setText("Oro");

        txtCantidadacomprar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCantidadacomprarKeyReleased(evt);
            }
        });

        jLabel4.setText("Cantidad a Comprar");

        javax.swing.GroupLayout pantallaDetalleOfertaLayout = new javax.swing.GroupLayout(pantallaDetalleOferta);
        pantallaDetalleOferta.setLayout(pantallaDetalleOfertaLayout);
        pantallaDetalleOfertaLayout.setHorizontalGroup(
                pantallaDetalleOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pantallaDetalleOfertaLayout.createSequentialGroup()
                                .addGroup(pantallaDetalleOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pantallaDetalleOfertaLayout.createSequentialGroup()
                                                .addGap(24, 24, 24)
                                                .addGroup(pantallaDetalleOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(pantallaDetalleOfertaLayout.createSequentialGroup()
                                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(lblNumeroOferta, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(pantallaDetalleOfertaLayout.createSequentialGroup()
                                                                .addGroup(pantallaDetalleOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                                                                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(pantallaDetalleOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(lblRecursoavender, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                                                        .addComponent(lblCantidadOfertada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(lblJugadorOferente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(lblRecursoBuscado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(txtCantidadacomprar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addGroup(pantallaDetalleOfertaLayout.createSequentialGroup()
                                                .addGap(97, 97, 97)
                                                .addComponent(cmcComprarOferta)))
                                .addContainerGap(20, Short.MAX_VALUE))
        );
        pantallaDetalleOfertaLayout.setVerticalGroup(
                pantallaDetalleOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pantallaDetalleOfertaLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(pantallaDetalleOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblNumeroOferta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pantallaDetalleOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(lblRecursoavender))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pantallaDetalleOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(lblCantidadOfertada))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                                .addGroup(pantallaDetalleOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(lblRecursoBuscado))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pantallaDetalleOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblJugadorOferente)
                                        .addComponent(jLabel7))
                                .addGap(4, 4, 4)
                                .addGroup(pantallaDetalleOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtCantidadacomprar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmcComprarOferta)
                                .addContainerGap())
        );

        panelImage1.add(pantallaDetalleOferta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        lstOfertas.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstOfertasValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstOfertas);

        panelImage1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 44, 112, 153));

        cboFiltro.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"Todos", "Madera", "Marmol", "Vino", "Cristal", "Azufre"}));
        cboFiltro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboFiltroItemStateChanged(evt);
            }
        });
        panelImage1.add(cboFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 11, 112, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(panelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(panelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmcComprarOfertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmcComprarOfertaActionPerformed
        if (!txtCantidadacomprar.getText().equals("")) {

            if (!ofertaelegida.isJugador()) {
                try {
                    ComprarRecursosaJuego comprarrecursoajuego = new ComprarRecursosaJuego(this.vciudad, this.ofertaelegida, Integer.parseInt(this.txtCantidadacomprar.getText()));
                    comprarrecursoajuego.CUcomprarrecursosajuego();
                    this.hide();
                } catch (SQLException ex) {
                    Logger.getLogger(VVerOferta.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                try {
                    OfertaJugador oferta = ((OfertaJugador) this.ofertaelegida);
                    ComprarRecursosdeJugador comprarrecursoajuego = new ComprarRecursosdeJugador(this.vciudad, oferta, Integer.parseInt(this.txtCantidadacomprar.getText()));
                    comprarrecursoajuego.CUcomprarrecursosdejugador();
                    this.hide();
                } catch (SQLException ex) {
                    Logger.getLogger(VVerOferta.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            this.vermercado.getVermercado().actualizardatospantalla();
        } else {
            JOptionPane.showMessageDialog(panelImage1, "Debes ingresar la cantidad que deseas comprar.");

        }
    }//GEN-LAST:event_cmcComprarOfertaActionPerformed

    private void lstOfertasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstOfertasValueChanged
        try {

            int ofertanumero = (int) this.lstOfertas.getSelectedValue();
            for (int i = 0; i < this.ofertas.size(); i++) {
                if (ofertanumero == this.ofertas.get(i).getCodigooferta()) {
                    int codigo = this.ofertas.get(i).getCodigooferta();
                    if (this.ofertas.get(i).isJugador()) {
                        this.ofertaelegida = new OfertaJugador();
                        this.ofertaelegida.setCodigooferta(codigo);
                        this.ofertaelegida.setJugador(true);
                    } else {
                        this.ofertaelegida = new Oferta();
                        this.ofertaelegida.setCodigooferta(codigo);
                        this.ofertaelegida.setJugador(false);
                    }

                }
            }

            VerOferta veroferta = new VerOferta(this.vciudad.getCiudad().getJugador(), this, this.ofertaelegida);
            veroferta.MostrarOferta();
        } catch (SQLException ex) {

        }
    }//GEN-LAST:event_lstOfertasValueChanged

    private void cboFiltroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboFiltroItemStateChanged
        int entero = this.cboFiltro.getSelectedIndex();
        ofertas = new ArrayList<>();
        String filtro = (String) this.cboFiltro.getModel().getSelectedItem();
        System.out.printf(filtro);
        VerOferta veroferta = new VerOferta(this.ofertas, filtro, this, this.vciudad.getCiudad().getJugador());
        veroferta.CUInicializarOfertas();
    }//GEN-LAST:event_cboFiltroItemStateChanged

    private void txtCantidadacomprarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadacomprarKeyReleased
        if (!"".equals(this.txtCantidadacomprar.getText())) {
            int numero;
            try {
                numero = Integer.parseInt(this.txtCantidadacomprar.getText());
                if (numero <= Integer.parseInt(this.lblCantidadOfertada.getText())) {

                } else {
                    this.txtCantidadacomprar.setText("");
                }

            } catch (NumberFormatException j) {
                this.txtCantidadacomprar.setText("");

            }
        }
    }//GEN-LAST:event_txtCantidadacomprarKeyReleased

    public List<Oferta> getOfertas() {
        return ofertas;
    }

    public JButton getCmcComprarOferta() {
        return cmcComprarOferta;
    }

    public JLabel getLblCantidadOfertada() {
        return lblCantidadOfertada;
    }

    public JLabel getLblJugadorOferente() {
        return lblJugadorOferente;
    }

    public JLabel getLblNumeroOferta() {
        return lblNumeroOferta;
    }

    public JLabel getLblRecursoavender() {
        return lblRecursoavender;
    }

    public JList getLstOfertas() {
        return lstOfertas;
    }
    // End of variables declaration//GEN-END:variables


}
