/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jmg.buzios.view.edificios;

import com.jmg.buzios.controller.edificio.VerDepositooAlmacen;
import org.edisoncor.gui.panel.PanelImage;

import javax.swing.*;
import java.sql.SQLException;

/**
 * @author Alumno
 */
public class VVerDepositooAlmacen extends javax.swing.JFrame {

    private VerDepositooAlmacen vdepositooalmacen;
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdDestruiredificio;
    private javax.swing.JButton cmdElevarniveledificio;
    private org.edisoncor.gui.panel.PanelImage edificioAcademia;
    private org.edisoncor.gui.panel.PanelImage imagenAzufre;
    private org.edisoncor.gui.panel.PanelImage imagenCristal;
    private org.edisoncor.gui.panel.PanelImage imagenMadera;
    private org.edisoncor.gui.panel.PanelImage imagenMarmol;
    private org.edisoncor.gui.panel.PanelImage imagenRecurso;
    private org.edisoncor.gui.panel.PanelImage imagenRecurso1;
    private org.edisoncor.gui.panel.PanelImage imagenRecurso2;
    private org.edisoncor.gui.panel.PanelImage imagenRecurso3;
    private org.edisoncor.gui.panel.PanelImage imagenRecurso4;
    private org.edisoncor.gui.panel.PanelImage imagenRecursoasegurado;
    private org.edisoncor.gui.panel.PanelImage imagenRecursoasegurado1;
    private org.edisoncor.gui.panel.PanelImage imagenRecursoasegurado2;
    private org.edisoncor.gui.panel.PanelImage imagenRecursoasegurado3;
    private org.edisoncor.gui.panel.PanelImage imagenRecursoasegurado4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblAzufre;
    private javax.swing.JLabel lblCantidadrecurso;
    private javax.swing.JLabel lblCantidadrecurso1;
    private javax.swing.JLabel lblCantidadrecurso2;
    private javax.swing.JLabel lblCantidadrecurso3;
    private javax.swing.JLabel lblCantidadrecurso4;
    private javax.swing.JLabel lblCantidadrecursoasegurado;
    private javax.swing.JLabel lblCantidadrecursoasegurado1;
    private javax.swing.JLabel lblCantidadrecursoasegurado2;
    private javax.swing.JLabel lblCantidadrecursoasegurado3;
    private javax.swing.JLabel lblCantidadrecursoasegurado4;
    private javax.swing.JLabel lblCristal;
    private javax.swing.JLabel lblMadera;
    private javax.swing.JLabel lblMarmol;
    private javax.swing.JLabel lblNivel;
    private javax.swing.JLabel lblNivelMaximo;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private org.edisoncor.gui.panel.PanelImage panelImage2;
    private org.edisoncor.gui.panel.PanelImage panelImage3;
    private org.edisoncor.gui.panel.PanelImage panelImage4;
    private org.edisoncor.gui.panel.PanelImage panelImage5;
    private org.edisoncor.gui.panel.PanelImage panelVentanaedificio;
    private org.edisoncor.gui.panel.PanelImage panelimagenedificio;
    public VVerDepositooAlmacen(VerDepositooAlmacen a) {
        initComponents();
        this.vdepositooalmacen = a;
        this.setLocationRelativeTo(null);
        this.show();
    }

    public JLabel getLblCantidadrecurso() {
        return lblCantidadrecurso;
    }

    public JLabel getLblCantidadrecurso1() {
        return lblCantidadrecurso1;
    }

    public JLabel getLblCantidadrecurso2() {
        return lblCantidadrecurso2;
    }

    public JLabel getLblCantidadrecurso3() {
        return lblCantidadrecurso3;
    }

    public JLabel getLblCantidadrecurso4() {
        return lblCantidadrecurso4;
    }

    public JLabel getLblCantidadrecursoasegurado() {
        return lblCantidadrecursoasegurado;
    }

    public JLabel getLblCantidadrecursoasegurado1() {
        return lblCantidadrecursoasegurado1;
    }

    public JLabel getLblCantidadrecursoasegurado2() {
        return lblCantidadrecursoasegurado2;
    }

    public JLabel getLblCantidadrecursoasegurado3() {
        return lblCantidadrecursoasegurado3;
    }

    public JLabel getLblCantidadrecursoasegurado4() {
        return lblCantidadrecursoasegurado4;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelVentanaedificio = new org.edisoncor.gui.panel.PanelImage();
        panelImage2 = new org.edisoncor.gui.panel.PanelImage();
        panelImage4 = new org.edisoncor.gui.panel.PanelImage();
        cmdDestruiredificio = new javax.swing.JButton();
        panelImage5 = new org.edisoncor.gui.panel.PanelImage();
        cmdElevarniveledificio = new javax.swing.JButton();
        imagenMadera = new org.edisoncor.gui.panel.PanelImage();
        imagenMarmol = new org.edisoncor.gui.panel.PanelImage();
        imagenAzufre = new org.edisoncor.gui.panel.PanelImage();
        imagenCristal = new org.edisoncor.gui.panel.PanelImage();
        lblCristal = new javax.swing.JLabel();
        lblAzufre = new javax.swing.JLabel();
        lblMarmol = new javax.swing.JLabel();
        lblMadera = new javax.swing.JLabel();
        panelimagenedificio = new org.edisoncor.gui.panel.PanelImage();
        lblNivel = new javax.swing.JLabel();
        lblNivelMaximo = new javax.swing.JLabel();
        panelImage3 = new org.edisoncor.gui.panel.PanelImage();
        edificioAcademia = new org.edisoncor.gui.panel.PanelImage();
        imagenRecurso = new org.edisoncor.gui.panel.PanelImage();
        lblCantidadrecurso = new javax.swing.JLabel();
        lblCantidadrecurso1 = new javax.swing.JLabel();
        imagenRecurso1 = new org.edisoncor.gui.panel.PanelImage();
        lblCantidadrecurso2 = new javax.swing.JLabel();
        imagenRecurso2 = new org.edisoncor.gui.panel.PanelImage();
        lblCantidadrecurso3 = new javax.swing.JLabel();
        imagenRecurso3 = new org.edisoncor.gui.panel.PanelImage();
        lblCantidadrecurso4 = new javax.swing.JLabel();
        imagenRecurso4 = new org.edisoncor.gui.panel.PanelImage();
        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        lblCantidadrecursoasegurado = new javax.swing.JLabel();
        imagenRecursoasegurado = new org.edisoncor.gui.panel.PanelImage();
        lblCantidadrecursoasegurado1 = new javax.swing.JLabel();
        imagenRecursoasegurado1 = new org.edisoncor.gui.panel.PanelImage();
        lblCantidadrecursoasegurado2 = new javax.swing.JLabel();
        imagenRecursoasegurado2 = new org.edisoncor.gui.panel.PanelImage();
        lblCantidadrecursoasegurado3 = new javax.swing.JLabel();
        imagenRecursoasegurado3 = new org.edisoncor.gui.panel.PanelImage();
        lblCantidadrecursoasegurado4 = new javax.swing.JLabel();
        imagenRecursoasegurado4 = new org.edisoncor.gui.panel.PanelImage();
        jLabel2 = new javax.swing.JLabel();

        setResizable(false);

        panelVentanaedificio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/backg-2.png"))); // NOI18N

        panelImage2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/backg-1.png"))); // NOI18N

        panelImage4.setOpaque(false);

        cmdDestruiredificio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/boton destruir edificio.png"))); // NOI18N
        cmdDestruiredificio.setBorder(null);
        cmdDestruiredificio.setContentAreaFilled(false);
        cmdDestruiredificio.setMargin(new java.awt.Insets(0, 0, 0, 0));
        cmdDestruiredificio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdDestruiredificioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelImage4Layout = new javax.swing.GroupLayout(panelImage4);
        panelImage4.setLayout(panelImage4Layout);
        panelImage4Layout.setHorizontalGroup(
                panelImage4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cmdDestruiredificio, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        panelImage4Layout.setVerticalGroup(
                panelImage4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cmdDestruiredificio, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        panelImage5.setOpaque(false);

        cmdElevarniveledificio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/boton elevar nivel.png"))); // NOI18N
        cmdElevarniveledificio.setAlignmentY(0.0F);
        cmdElevarniveledificio.setBorder(null);
        cmdElevarniveledificio.setContentAreaFilled(false);
        cmdElevarniveledificio.setMargin(new java.awt.Insets(0, 0, 0, 0));
        cmdElevarniveledificio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdElevarniveledificioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelImage5Layout = new javax.swing.GroupLayout(panelImage5);
        panelImage5.setLayout(panelImage5Layout);
        panelImage5Layout.setHorizontalGroup(
                panelImage5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cmdElevarniveledificio)
        );
        panelImage5Layout.setVerticalGroup(
                panelImage5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cmdElevarniveledificio)
        );

        imagenMadera.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        imagenMadera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/Maderadeedificionivel.jpg"))); // NOI18N

        javax.swing.GroupLayout imagenMaderaLayout = new javax.swing.GroupLayout(imagenMadera);
        imagenMadera.setLayout(imagenMaderaLayout);
        imagenMaderaLayout.setHorizontalGroup(
                imagenMaderaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 49, Short.MAX_VALUE)
        );
        imagenMaderaLayout.setVerticalGroup(
                imagenMaderaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 45, Short.MAX_VALUE)
        );

        imagenMarmol.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        imagenMarmol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/Marmoldeedificionivel.jpg"))); // NOI18N

        javax.swing.GroupLayout imagenMarmolLayout = new javax.swing.GroupLayout(imagenMarmol);
        imagenMarmol.setLayout(imagenMarmolLayout);
        imagenMarmolLayout.setHorizontalGroup(
                imagenMarmolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 49, Short.MAX_VALUE)
        );
        imagenMarmolLayout.setVerticalGroup(
                imagenMarmolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 45, Short.MAX_VALUE)
        );

        imagenAzufre.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        imagenAzufre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/Azufredeedificionivel.jpg"))); // NOI18N

        javax.swing.GroupLayout imagenAzufreLayout = new javax.swing.GroupLayout(imagenAzufre);
        imagenAzufre.setLayout(imagenAzufreLayout);
        imagenAzufreLayout.setHorizontalGroup(
                imagenAzufreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 49, Short.MAX_VALUE)
        );
        imagenAzufreLayout.setVerticalGroup(
                imagenAzufreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 45, Short.MAX_VALUE)
        );

        imagenCristal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        imagenCristal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/Cristaldeedificionivel.jpg"))); // NOI18N

        javax.swing.GroupLayout imagenCristalLayout = new javax.swing.GroupLayout(imagenCristal);
        imagenCristal.setLayout(imagenCristalLayout);
        imagenCristalLayout.setHorizontalGroup(
                imagenCristalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 49, Short.MAX_VALUE)
        );
        imagenCristalLayout.setVerticalGroup(
                imagenCristalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 45, Short.MAX_VALUE)
        );

        lblCristal.setText("0");

        lblAzufre.setText("0");

        lblMarmol.setText("0");

        lblMadera.setText("0");

        panelimagenedificio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelimagenedificio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/fondoblanco.png"))); // NOI18N

        lblNivel.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lblNivel.setText("01");

        lblNivelMaximo.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblNivelMaximo.setText("Nivel Máximo");

        javax.swing.GroupLayout panelimagenedificioLayout = new javax.swing.GroupLayout(panelimagenedificio);
        panelimagenedificio.setLayout(panelimagenedificioLayout);
        panelimagenedificioLayout.setHorizontalGroup(
                panelimagenedificioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelimagenedificioLayout.createSequentialGroup()
                                .addGroup(panelimagenedificioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelimagenedificioLayout.createSequentialGroup()
                                                .addGap(84, 84, 84)
                                                .addComponent(lblNivel))
                                        .addGroup(panelimagenedificioLayout.createSequentialGroup()
                                                .addGap(66, 66, 66)
                                                .addComponent(lblNivelMaximo)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelimagenedificioLayout.setVerticalGroup(
                panelimagenedificioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelimagenedificioLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblNivelMaximo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNivel)
                                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout panelImage2Layout = new javax.swing.GroupLayout(panelImage2);
        panelImage2.setLayout(panelImage2Layout);
        panelImage2Layout.setHorizontalGroup(
                panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelImage2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(panelimagenedificio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(panelImage2Layout.createSequentialGroup()
                                                .addGroup(panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelImage2Layout.createSequentialGroup()
                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                .addGroup(panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(lblMadera, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(imagenMadera, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(imagenMarmol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(lblMarmol, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addComponent(panelImage5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(10, 10, 10)
                                                .addGroup(panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(panelImage2Layout.createSequentialGroup()
                                                                .addGroup(panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(lblAzufre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(imagenAzufre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(lblCristal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(imagenCristal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addComponent(panelImage4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addContainerGap())
        );
        panelImage2Layout.setVerticalGroup(
                panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImage2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(panelimagenedificio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(panelImage5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(panelImage4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(panelImage2Layout.createSequentialGroup()
                                                        .addComponent(imagenCristal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(lblCristal))
                                                .addGroup(panelImage2Layout.createSequentialGroup()
                                                        .addComponent(imagenAzufre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(lblAzufre))
                                                .addGroup(panelImage2Layout.createSequentialGroup()
                                                        .addComponent(imagenMarmol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(20, 20, 20)))
                                        .addGroup(panelImage2Layout.createSequentialGroup()
                                                .addComponent(imagenMadera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(lblMadera)
                                                        .addComponent(lblMarmol))))
                                .addContainerGap())
        );

        panelImage3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelImage3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/back-3.png"))); // NOI18N

        edificioAcademia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        edificioAcademia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/backg-2.png"))); // NOI18N

        imagenRecurso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        imagenRecurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/Maderadeedificionivel100x100.png"))); // NOI18N

        javax.swing.GroupLayout imagenRecursoLayout = new javax.swing.GroupLayout(imagenRecurso);
        imagenRecurso.setLayout(imagenRecursoLayout);
        imagenRecursoLayout.setHorizontalGroup(
                imagenRecursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );
        imagenRecursoLayout.setVerticalGroup(
                imagenRecursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 77, Short.MAX_VALUE)
        );

        lblCantidadrecurso.setText("0");

        lblCantidadrecurso1.setText("0");

        imagenRecurso1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        imagenRecurso1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/Marmoldeedificionivel100x100.png"))); // NOI18N

        javax.swing.GroupLayout imagenRecurso1Layout = new javax.swing.GroupLayout(imagenRecurso1);
        imagenRecurso1.setLayout(imagenRecurso1Layout);
        imagenRecurso1Layout.setHorizontalGroup(
                imagenRecurso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );
        imagenRecurso1Layout.setVerticalGroup(
                imagenRecurso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 77, Short.MAX_VALUE)
        );

        lblCantidadrecurso2.setText("0");

        imagenRecurso2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        imagenRecurso2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/Azufredeedificionivel100x100.png"))); // NOI18N

        javax.swing.GroupLayout imagenRecurso2Layout = new javax.swing.GroupLayout(imagenRecurso2);
        imagenRecurso2.setLayout(imagenRecurso2Layout);
        imagenRecurso2Layout.setHorizontalGroup(
                imagenRecurso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );
        imagenRecurso2Layout.setVerticalGroup(
                imagenRecurso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 77, Short.MAX_VALUE)
        );

        lblCantidadrecurso3.setText("0");

        imagenRecurso3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        imagenRecurso3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/Cristaldeedificionivel100x100.png"))); // NOI18N

        javax.swing.GroupLayout imagenRecurso3Layout = new javax.swing.GroupLayout(imagenRecurso3);
        imagenRecurso3.setLayout(imagenRecurso3Layout);
        imagenRecurso3Layout.setHorizontalGroup(
                imagenRecurso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );
        imagenRecurso3Layout.setVerticalGroup(
                imagenRecurso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 77, Short.MAX_VALUE)
        );

        lblCantidadrecurso4.setText("0");

        imagenRecurso4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        imagenRecurso4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/VinoImg100x100.png"))); // NOI18N

        javax.swing.GroupLayout imagenRecurso4Layout = new javax.swing.GroupLayout(imagenRecurso4);
        imagenRecurso4.setLayout(imagenRecurso4Layout);
        imagenRecurso4Layout.setHorizontalGroup(
                imagenRecurso4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );
        imagenRecurso4Layout.setVerticalGroup(
                imagenRecurso4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 77, Short.MAX_VALUE)
        );

        panelImage1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/backg-1.png"))); // NOI18N

        lblCantidadrecursoasegurado.setText("0");

        imagenRecursoasegurado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        imagenRecursoasegurado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/Maderadeedificionivel100x100.png"))); // NOI18N

        javax.swing.GroupLayout imagenRecursoaseguradoLayout = new javax.swing.GroupLayout(imagenRecursoasegurado);
        imagenRecursoasegurado.setLayout(imagenRecursoaseguradoLayout);
        imagenRecursoaseguradoLayout.setHorizontalGroup(
                imagenRecursoaseguradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );
        imagenRecursoaseguradoLayout.setVerticalGroup(
                imagenRecursoaseguradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 77, Short.MAX_VALUE)
        );

        lblCantidadrecursoasegurado1.setText("0");

        imagenRecursoasegurado1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        imagenRecursoasegurado1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/Marmoldeedificionivel100x100.png"))); // NOI18N

        javax.swing.GroupLayout imagenRecursoasegurado1Layout = new javax.swing.GroupLayout(imagenRecursoasegurado1);
        imagenRecursoasegurado1.setLayout(imagenRecursoasegurado1Layout);
        imagenRecursoasegurado1Layout.setHorizontalGroup(
                imagenRecursoasegurado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );
        imagenRecursoasegurado1Layout.setVerticalGroup(
                imagenRecursoasegurado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 77, Short.MAX_VALUE)
        );

        lblCantidadrecursoasegurado2.setText("0");

        imagenRecursoasegurado2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        imagenRecursoasegurado2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/Azufredeedificionivel100x100.png"))); // NOI18N

        javax.swing.GroupLayout imagenRecursoasegurado2Layout = new javax.swing.GroupLayout(imagenRecursoasegurado2);
        imagenRecursoasegurado2.setLayout(imagenRecursoasegurado2Layout);
        imagenRecursoasegurado2Layout.setHorizontalGroup(
                imagenRecursoasegurado2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );
        imagenRecursoasegurado2Layout.setVerticalGroup(
                imagenRecursoasegurado2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 77, Short.MAX_VALUE)
        );

        lblCantidadrecursoasegurado3.setText("0");

        imagenRecursoasegurado3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        imagenRecursoasegurado3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/Cristaldeedificionivel100x100.png"))); // NOI18N

        javax.swing.GroupLayout imagenRecursoasegurado3Layout = new javax.swing.GroupLayout(imagenRecursoasegurado3);
        imagenRecursoasegurado3.setLayout(imagenRecursoasegurado3Layout);
        imagenRecursoasegurado3Layout.setHorizontalGroup(
                imagenRecursoasegurado3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );
        imagenRecursoasegurado3Layout.setVerticalGroup(
                imagenRecursoasegurado3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 77, Short.MAX_VALUE)
        );

        lblCantidadrecursoasegurado4.setText("0");

        imagenRecursoasegurado4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        imagenRecursoasegurado4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/VinoImg100x100.png"))); // NOI18N

        javax.swing.GroupLayout imagenRecursoasegurado4Layout = new javax.swing.GroupLayout(imagenRecursoasegurado4);
        imagenRecursoasegurado4.setLayout(imagenRecursoasegurado4Layout);
        imagenRecursoasegurado4Layout.setHorizontalGroup(
                imagenRecursoasegurado4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );
        imagenRecursoasegurado4Layout.setVerticalGroup(
                imagenRecursoasegurado4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 77, Short.MAX_VALUE)
        );

        jLabel2.setText("Capacidad de Recursos");

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
                panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelImage1Layout.createSequentialGroup()
                                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelImage1Layout.createSequentialGroup()
                                                .addGap(23, 23, 23)
                                                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(imagenRecursoasegurado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(lblCantidadrecursoasegurado, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(imagenRecursoasegurado1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(lblCantidadrecursoasegurado1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(imagenRecursoasegurado2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(lblCantidadrecursoasegurado2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(imagenRecursoasegurado3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(lblCantidadrecursoasegurado3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(imagenRecursoasegurado4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(lblCantidadrecursoasegurado4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(panelImage1Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(19, Short.MAX_VALUE))
        );
        panelImage1Layout.setVerticalGroup(
                panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelImage1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(panelImage1Layout.createSequentialGroup()
                                                .addComponent(imagenRecursoasegurado4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblCantidadrecursoasegurado4))
                                        .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(panelImage1Layout.createSequentialGroup()
                                                        .addComponent(imagenRecursoasegurado3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(lblCantidadrecursoasegurado3))
                                                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImage1Layout.createSequentialGroup()
                                                                .addComponent(imagenRecursoasegurado2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(lblCantidadrecursoasegurado2))
                                                        .addGroup(panelImage1Layout.createSequentialGroup()
                                                                .addComponent(imagenRecursoasegurado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(lblCantidadrecursoasegurado1))
                                                        .addGroup(panelImage1Layout.createSequentialGroup()
                                                                .addComponent(imagenRecursoasegurado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(lblCantidadrecursoasegurado)))))
                                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout edificioAcademiaLayout = new javax.swing.GroupLayout(edificioAcademia);
        edificioAcademia.setLayout(edificioAcademiaLayout);
        edificioAcademiaLayout.setHorizontalGroup(
                edificioAcademiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(edificioAcademiaLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(edificioAcademiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(imagenRecurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblCantidadrecurso, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(edificioAcademiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(imagenRecurso1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblCantidadrecurso1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(edificioAcademiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(imagenRecurso2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblCantidadrecurso2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(edificioAcademiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(imagenRecurso3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblCantidadrecurso3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(edificioAcademiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(imagenRecurso4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblCantidadrecurso4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, edificioAcademiaLayout.createSequentialGroup()
                                .addContainerGap(13, Short.MAX_VALUE)
                                .addComponent(panelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20))
        );
        edificioAcademiaLayout.setVerticalGroup(
                edificioAcademiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(edificioAcademiaLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(edificioAcademiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(edificioAcademiaLayout.createSequentialGroup()
                                                .addComponent(imagenRecurso4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblCantidadrecurso4))
                                        .addGroup(edificioAcademiaLayout.createSequentialGroup()
                                                .addComponent(imagenRecurso3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblCantidadrecurso3))
                                        .addGroup(edificioAcademiaLayout.createSequentialGroup()
                                                .addComponent(imagenRecurso2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblCantidadrecurso2))
                                        .addGroup(edificioAcademiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(edificioAcademiaLayout.createSequentialGroup()
                                                        .addComponent(imagenRecurso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(lblCantidadrecurso1))
                                                .addGroup(edificioAcademiaLayout.createSequentialGroup()
                                                        .addComponent(imagenRecurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(lblCantidadrecurso))))
                                .addGap(18, 18, 18)
                                .addComponent(panelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelImage3Layout = new javax.swing.GroupLayout(panelImage3);
        panelImage3.setLayout(panelImage3Layout);
        panelImage3Layout.setHorizontalGroup(
                panelImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelImage3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(edificioAcademia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelImage3Layout.setVerticalGroup(
                panelImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelImage3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(edificioAcademia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelVentanaedificioLayout = new javax.swing.GroupLayout(panelVentanaedificio);
        panelVentanaedificio.setLayout(panelVentanaedificioLayout);
        panelVentanaedificioLayout.setHorizontalGroup(
                panelVentanaedificioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelVentanaedificioLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(panelImage2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(panelImage3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(20, Short.MAX_VALUE))
        );
        panelVentanaedificioLayout.setVerticalGroup(
                panelVentanaedificioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelVentanaedificioLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panelVentanaedificioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(panelImage3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(panelImage2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelVentanaedificio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelVentanaedificio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdDestruiredificioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdDestruiredificioActionPerformed
        try {
            this.vdepositooalmacen.destruiredificio();
        } catch (SQLException ex) {

        }
    }//GEN-LAST:event_cmdDestruiredificioActionPerformed

    private void cmdElevarniveledificioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdElevarniveledificioActionPerformed
        try {
            this.vdepositooalmacen.elevarniveledificio();
        } catch (SQLException ex) {

        }
    }//GEN-LAST:event_cmdElevarniveledificioActionPerformed

    public JButton getCmdDestruiredificio() {
        return cmdDestruiredificio;
    }

    public JButton getCmdElevarniveledificio() {
        return cmdElevarniveledificio;
    }

    public PanelImage getImagenAzufre() {
        return imagenAzufre;
    }

    public PanelImage getImagenCristal() {
        return imagenCristal;
    }

    public PanelImage getImagenMadera() {
        return imagenMadera;
    }

    public PanelImage getImagenMarmol() {
        return imagenMarmol;
    }

    public JLabel getLblAzufre() {
        return lblAzufre;
    }

    public JLabel getLblCristal() {
        return lblCristal;
    }

    public JLabel getLblMadera() {
        return lblMadera;
    }

    public JLabel getLblMarmol() {
        return lblMarmol;
    }

    public JLabel getLblNivel() {
        return lblNivel;
    }

    public JLabel getLblNivelMaximo() {
        return lblNivelMaximo;
    }
    // End of variables declaration//GEN-END:variables
}
