/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jmg.buzios.view.edificios;

import com.jmg.buzios.controller.edificio.ConstruirEdificio;
import com.jmg.buzios.controller.edificio.VerPuerto;
import com.jmg.buzios.controller.puerto.ComprarBarcoMercante;
import com.jmg.buzios.model.ciudad.Ciudad;
import com.jmg.buzios.model.militar.acciones.Barco;
import com.jmg.buzios.view.islas.VEnviarRecurso;
import org.edisoncor.gui.panel.PanelImage;

import javax.swing.*;
import java.sql.SQLException;

/**
 * @author Alumno
 */
public class VVerPuerto extends javax.swing.JFrame {

    private VerPuerto verpuerto;


    private Barco barcoacomprar;
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdComprarbarcomercante;
    private javax.swing.JButton cmdDestruiredificio;
    private javax.swing.JButton cmdElevarniveledificio;
    private org.edisoncor.gui.panel.PanelImage edificioAcademia;
    private org.edisoncor.gui.panel.PanelImage imagenAzufre;
    private org.edisoncor.gui.panel.PanelImage imagenBarcosenventa;
    private org.edisoncor.gui.panel.PanelImage imagenCCiudad;
    private org.edisoncor.gui.panel.PanelImage imagenCCiudad1;
    private org.edisoncor.gui.panel.PanelImage imagenCCiudad2;
    private org.edisoncor.gui.panel.PanelImage imagenCCiudad3;
    private org.edisoncor.gui.panel.PanelImage imagenCCiudad4;
    private org.edisoncor.gui.panel.PanelImage imagenCCiudad5;
    private org.edisoncor.gui.panel.PanelImage imagenCCiudad6;
    private org.edisoncor.gui.panel.PanelImage imagenCCiudad7;
    private javax.swing.JButton imagenCiudad;
    private javax.swing.JButton imagenCiudad1;
    private javax.swing.JButton imagenCiudad2;
    private javax.swing.JButton imagenCiudad3;
    private javax.swing.JButton imagenCiudad4;
    private javax.swing.JButton imagenCiudad5;
    private javax.swing.JButton imagenCiudad6;
    private javax.swing.JButton imagenCiudad7;
    private org.edisoncor.gui.panel.PanelImage imagenCristal;
    private org.edisoncor.gui.panel.PanelImage imagenMadera;
    private org.edisoncor.gui.panel.PanelImage imagenMarmol;
    private javax.swing.JLabel lblAzufre;
    private javax.swing.JLabel lblCoordenadas;
    private javax.swing.JLabel lblCoordenadas1;
    private javax.swing.JLabel lblCoordenadas2;
    private javax.swing.JLabel lblCoordenadas3;
    private javax.swing.JLabel lblCoordenadas4;
    private javax.swing.JLabel lblCoordenadas5;
    private javax.swing.JLabel lblCoordenadas6;
    private javax.swing.JLabel lblCoordenadas7;
    private javax.swing.JLabel lblCristal;
    private javax.swing.JLabel lblMadera;
    private javax.swing.JLabel lblMarmol;
    private javax.swing.JLabel lblNivel;
    private javax.swing.JLabel lblNivelMaximo;
    private javax.swing.JLabel lblNombreCiudad;
    private javax.swing.JLabel lblNombreCiudad1;
    private javax.swing.JLabel lblNombreCiudad2;
    private javax.swing.JLabel lblNombreCiudad3;
    private javax.swing.JLabel lblNombreCiudad4;
    private javax.swing.JLabel lblNombreCiudad5;
    private javax.swing.JLabel lblNombreCiudad6;
    private javax.swing.JLabel lblNombreCiudad7;
    private org.edisoncor.gui.panel.PanelImage panelImage2;
    private org.edisoncor.gui.panel.PanelImage panelImage3;
    private org.edisoncor.gui.panel.PanelImage panelImage4;
    private org.edisoncor.gui.panel.PanelImage panelImage5;
    private org.edisoncor.gui.panel.PanelImage panelVentanaedificio;
    private org.edisoncor.gui.panel.PanelImage panelimagenedificio;

    public VVerPuerto(VerPuerto verpuerto) {
        initComponents();
        this.verpuerto = verpuerto;
        this.imagenCCiudad.setVisible(false);
        this.imagenCCiudad1.setVisible(false);
        this.imagenCCiudad2.setVisible(false);
        this.imagenCCiudad3.setVisible(false);
        this.imagenCCiudad4.setVisible(false);
        this.imagenCCiudad5.setVisible(false);
        this.imagenCCiudad6.setVisible(false);
        this.imagenCCiudad7.setVisible(false);
        this.barcoacomprar = Barco.inicializar_barco_mercante();
        this.setLocationRelativeTo(null);
        this.show();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelVentanaedificio = new org.edisoncor.gui.panel.PanelImage();
        panelImage2 = new org.edisoncor.gui.panel.PanelImage();
        panelImage4 = new org.edisoncor.gui.panel.PanelImage();
        cmdDestruiredificio = new javax.swing.JButton();
        panelImage5 = new org.edisoncor.gui.panel.PanelImage();
        cmdElevarniveledificio = new javax.swing.JButton();
        imagenMadera = new org.edisoncor.gui.panel.PanelImage();
        imagenMarmol = new org.edisoncor.gui.panel.PanelImage();
        imagenAzufre = new org.edisoncor.gui.panel.PanelImage();
        imagenCristal = new org.edisoncor.gui.panel.PanelImage();
        lblCristal = new javax.swing.JLabel();
        lblAzufre = new javax.swing.JLabel();
        lblMarmol = new javax.swing.JLabel();
        lblMadera = new javax.swing.JLabel();
        panelimagenedificio = new org.edisoncor.gui.panel.PanelImage();
        lblNivel = new javax.swing.JLabel();
        lblNivelMaximo = new javax.swing.JLabel();
        panelImage3 = new org.edisoncor.gui.panel.PanelImage();
        edificioAcademia = new org.edisoncor.gui.panel.PanelImage();
        imagenCCiudad = new org.edisoncor.gui.panel.PanelImage();
        imagenCiudad = new javax.swing.JButton();
        lblNombreCiudad = new javax.swing.JLabel();
        lblCoordenadas = new javax.swing.JLabel();
        imagenCCiudad1 = new org.edisoncor.gui.panel.PanelImage();
        imagenCiudad1 = new javax.swing.JButton();
        lblNombreCiudad1 = new javax.swing.JLabel();
        lblCoordenadas1 = new javax.swing.JLabel();
        imagenCCiudad2 = new org.edisoncor.gui.panel.PanelImage();
        imagenCiudad2 = new javax.swing.JButton();
        lblNombreCiudad2 = new javax.swing.JLabel();
        lblCoordenadas2 = new javax.swing.JLabel();
        imagenCCiudad3 = new org.edisoncor.gui.panel.PanelImage();
        imagenCiudad3 = new javax.swing.JButton();
        lblNombreCiudad3 = new javax.swing.JLabel();
        lblCoordenadas3 = new javax.swing.JLabel();
        imagenCCiudad4 = new org.edisoncor.gui.panel.PanelImage();
        imagenCiudad4 = new javax.swing.JButton();
        lblNombreCiudad4 = new javax.swing.JLabel();
        lblCoordenadas4 = new javax.swing.JLabel();
        imagenCCiudad5 = new org.edisoncor.gui.panel.PanelImage();
        imagenCiudad5 = new javax.swing.JButton();
        lblNombreCiudad5 = new javax.swing.JLabel();
        lblCoordenadas5 = new javax.swing.JLabel();
        imagenCCiudad6 = new org.edisoncor.gui.panel.PanelImage();
        imagenCiudad6 = new javax.swing.JButton();
        lblNombreCiudad6 = new javax.swing.JLabel();
        lblCoordenadas6 = new javax.swing.JLabel();
        imagenCCiudad7 = new org.edisoncor.gui.panel.PanelImage();
        imagenCiudad7 = new javax.swing.JButton();
        lblNombreCiudad7 = new javax.swing.JLabel();
        lblCoordenadas7 = new javax.swing.JLabel();
        imagenBarcosenventa = new org.edisoncor.gui.panel.PanelImage();
        cmdComprarbarcomercante = new javax.swing.JButton();

        setResizable(false);

        panelVentanaedificio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/back-3.png"))); // NOI18N
        panelVentanaedificio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelImage2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/backg-1.png"))); // NOI18N
        panelImage2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelImage4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cmdDestruiredificio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/boton destruir edificio.png"))); // NOI18N
        cmdDestruiredificio.setBorderPainted(false);
        cmdDestruiredificio.setContentAreaFilled(false);
        cmdDestruiredificio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdDestruiredificioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelImage4Layout = new javax.swing.GroupLayout(panelImage4);
        panelImage4.setLayout(panelImage4Layout);
        panelImage4Layout.setHorizontalGroup(
                panelImage4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelImage4Layout.createSequentialGroup()
                                .addComponent(cmdDestruiredificio, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelImage4Layout.setVerticalGroup(
                panelImage4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelImage4Layout.createSequentialGroup()
                                .addComponent(cmdDestruiredificio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, Short.MAX_VALUE)
                                .addGap(0, 0, 0))
        );

        panelImage2.add(panelImage4, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 147, 112, -1));

        panelImage5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cmdElevarniveledificio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/boton elevar nivel.png"))); // NOI18N
        cmdElevarniveledificio.setBorderPainted(false);
        cmdElevarniveledificio.setContentAreaFilled(false);
        cmdElevarniveledificio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdElevarniveledificioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelImage5Layout = new javax.swing.GroupLayout(panelImage5);
        panelImage5.setLayout(panelImage5Layout);
        panelImage5Layout.setHorizontalGroup(
                panelImage5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cmdElevarniveledificio, javax.swing.GroupLayout.PREFERRED_SIZE, 110, Short.MAX_VALUE)
        );
        panelImage5Layout.setVerticalGroup(
                panelImage5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelImage5Layout.createSequentialGroup()
                                .addComponent(cmdElevarniveledificio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, Short.MAX_VALUE)
                                .addContainerGap())
        );

        panelImage2.add(panelImage5, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 147, 112, 54));

        imagenMadera.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        imagenMadera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/Maderadeedificionivel100x100.png"))); // NOI18N

        javax.swing.GroupLayout imagenMaderaLayout = new javax.swing.GroupLayout(imagenMadera);
        imagenMadera.setLayout(imagenMaderaLayout);
        imagenMaderaLayout.setHorizontalGroup(
                imagenMaderaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 49, Short.MAX_VALUE)
        );
        imagenMaderaLayout.setVerticalGroup(
                imagenMaderaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 45, Short.MAX_VALUE)
        );

        panelImage2.add(imagenMadera, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 207, -1, -1));

        imagenMarmol.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        imagenMarmol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/Marmoldeedificionivel100x100.png"))); // NOI18N

        javax.swing.GroupLayout imagenMarmolLayout = new javax.swing.GroupLayout(imagenMarmol);
        imagenMarmol.setLayout(imagenMarmolLayout);
        imagenMarmolLayout.setHorizontalGroup(
                imagenMarmolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 49, Short.MAX_VALUE)
        );
        imagenMarmolLayout.setVerticalGroup(
                imagenMarmolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 45, Short.MAX_VALUE)
        );

        panelImage2.add(imagenMarmol, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 207, -1, -1));

        imagenAzufre.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        imagenAzufre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/Azufredeedificionivel100x100.png"))); // NOI18N

        javax.swing.GroupLayout imagenAzufreLayout = new javax.swing.GroupLayout(imagenAzufre);
        imagenAzufre.setLayout(imagenAzufreLayout);
        imagenAzufreLayout.setHorizontalGroup(
                imagenAzufreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 49, Short.MAX_VALUE)
        );
        imagenAzufreLayout.setVerticalGroup(
                imagenAzufreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 45, Short.MAX_VALUE)
        );

        panelImage2.add(imagenAzufre, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 207, -1, -1));

        imagenCristal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        imagenCristal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/Cristaldeedificionivel100x100.png"))); // NOI18N

        javax.swing.GroupLayout imagenCristalLayout = new javax.swing.GroupLayout(imagenCristal);
        imagenCristal.setLayout(imagenCristalLayout);
        imagenCristalLayout.setHorizontalGroup(
                imagenCristalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 49, Short.MAX_VALUE)
        );
        imagenCristalLayout.setVerticalGroup(
                imagenCristalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 45, Short.MAX_VALUE)
        );

        panelImage2.add(imagenCristal, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 207, -1, -1));

        lblCristal.setText("0");
        panelImage2.add(lblCristal, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 262, 53, -1));

        lblAzufre.setText("0");
        panelImage2.add(lblAzufre, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 262, 53, -1));

        lblMarmol.setText("0");
        panelImage2.add(lblMarmol, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 262, 53, -1));

        lblMadera.setText("0");
        panelImage2.add(lblMadera, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 262, 53, -1));

        panelimagenedificio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelimagenedificio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/fondoblanco.png"))); // NOI18N

        lblNivel.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lblNivel.setText("01");

        lblNivelMaximo.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblNivelMaximo.setText("Nivel Máximo");

        javax.swing.GroupLayout panelimagenedificioLayout = new javax.swing.GroupLayout(panelimagenedificio);
        panelimagenedificio.setLayout(panelimagenedificioLayout);
        panelimagenedificioLayout.setHorizontalGroup(
                panelimagenedificioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelimagenedificioLayout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addGroup(panelimagenedificioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelimagenedificioLayout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(lblNivel))
                                        .addComponent(lblNivelMaximo))
                                .addContainerGap(73, Short.MAX_VALUE))
        );
        panelimagenedificioLayout.setVerticalGroup(
                panelimagenedificioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelimagenedificioLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblNivelMaximo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNivel)
                                .addContainerGap(34, Short.MAX_VALUE))
        );

        panelImage2.add(panelimagenedificio, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 12, 234, -1));

        panelVentanaedificio.add(panelImage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 260, 290));

        panelImage3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelImage3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/backg-1.png"))); // NOI18N
        panelImage3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        edificioAcademia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        edificioAcademia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/backg-2-330-260.png"))); // NOI18N
        edificioAcademia.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imagenCCiudad.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        imagenCCiudad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/backg-2-330-260.png"))); // NOI18N

        imagenCiudad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/ISLA/imagenciudad1.png"))); // NOI18N
        imagenCiudad.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        imagenCiudad.setBorderPainted(false);
        imagenCiudad.setContentAreaFilled(false);
        imagenCiudad.setFocusable(false);
        imagenCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imagenCiudadActionPerformed(evt);
            }
        });

        lblNombreCiudad.setText("Ciuda del Fuego");

        lblCoordenadas.setText("39:87 - Enduos");

        javax.swing.GroupLayout imagenCCiudadLayout = new javax.swing.GroupLayout(imagenCCiudad);
        imagenCCiudad.setLayout(imagenCCiudadLayout);
        imagenCCiudadLayout.setHorizontalGroup(
                imagenCCiudadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(imagenCCiudadLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(imagenCCiudadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(imagenCiudad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblNombreCiudad, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                                        .addComponent(lblCoordenadas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        imagenCCiudadLayout.setVerticalGroup(
                imagenCCiudadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(imagenCCiudadLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(imagenCiudad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNombreCiudad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCoordenadas)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        edificioAcademia.add(imagenCCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 12, -1, -1));

        imagenCCiudad1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        imagenCCiudad1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/backg-2-330-260.png"))); // NOI18N

        imagenCiudad1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/ISLA/imagenciudad1.png"))); // NOI18N
        imagenCiudad1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        imagenCiudad1.setBorderPainted(false);
        imagenCiudad1.setContentAreaFilled(false);
        imagenCiudad1.setFocusable(false);
        imagenCiudad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imagenCiudad1ActionPerformed(evt);
            }
        });

        lblNombreCiudad1.setText("Ciuda del Fuego");

        lblCoordenadas1.setText("39:87 - Enduos");

        javax.swing.GroupLayout imagenCCiudad1Layout = new javax.swing.GroupLayout(imagenCCiudad1);
        imagenCCiudad1.setLayout(imagenCCiudad1Layout);
        imagenCCiudad1Layout.setHorizontalGroup(
                imagenCCiudad1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(imagenCCiudad1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(imagenCCiudad1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(imagenCiudad1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblNombreCiudad1, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                                        .addComponent(lblCoordenadas1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        imagenCCiudad1Layout.setVerticalGroup(
                imagenCCiudad1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(imagenCCiudad1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(imagenCiudad1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNombreCiudad1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCoordenadas1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        edificioAcademia.add(imagenCCiudad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 12, -1, -1));

        imagenCCiudad2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        imagenCCiudad2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/backg-2-330-260.png"))); // NOI18N

        imagenCiudad2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/ISLA/imagenciudad1.png"))); // NOI18N
        imagenCiudad2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        imagenCiudad2.setBorderPainted(false);
        imagenCiudad2.setContentAreaFilled(false);
        imagenCiudad2.setFocusable(false);
        imagenCiudad2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imagenCiudad2ActionPerformed(evt);
            }
        });

        lblNombreCiudad2.setText("Ciuda del Fuego");

        lblCoordenadas2.setText("39:87 - Enduos");

        javax.swing.GroupLayout imagenCCiudad2Layout = new javax.swing.GroupLayout(imagenCCiudad2);
        imagenCCiudad2.setLayout(imagenCCiudad2Layout);
        imagenCCiudad2Layout.setHorizontalGroup(
                imagenCCiudad2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(imagenCCiudad2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(imagenCCiudad2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(imagenCiudad2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblNombreCiudad2, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                                        .addComponent(lblCoordenadas2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        imagenCCiudad2Layout.setVerticalGroup(
                imagenCCiudad2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(imagenCCiudad2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(imagenCiudad2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNombreCiudad2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCoordenadas2)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        edificioAcademia.add(imagenCCiudad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 12, -1, -1));

        imagenCCiudad3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        imagenCCiudad3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/backg-2-330-260.png"))); // NOI18N

        imagenCiudad3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/ISLA/imagenciudad1.png"))); // NOI18N
        imagenCiudad3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        imagenCiudad3.setBorderPainted(false);
        imagenCiudad3.setContentAreaFilled(false);
        imagenCiudad3.setFocusable(false);
        imagenCiudad3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imagenCiudad3ActionPerformed(evt);
            }
        });

        lblNombreCiudad3.setText("Ciuda del Fuego");

        lblCoordenadas3.setText("39:87 - Enduos");

        javax.swing.GroupLayout imagenCCiudad3Layout = new javax.swing.GroupLayout(imagenCCiudad3);
        imagenCCiudad3.setLayout(imagenCCiudad3Layout);
        imagenCCiudad3Layout.setHorizontalGroup(
                imagenCCiudad3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(imagenCCiudad3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(imagenCCiudad3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(imagenCiudad3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblNombreCiudad3, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                                        .addComponent(lblCoordenadas3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        imagenCCiudad3Layout.setVerticalGroup(
                imagenCCiudad3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(imagenCCiudad3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(imagenCiudad3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNombreCiudad3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCoordenadas3)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        edificioAcademia.add(imagenCCiudad3, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 12, -1, -1));

        imagenCCiudad4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        imagenCCiudad4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/backg-2-330-260.png"))); // NOI18N

        imagenCiudad4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/ISLA/imagenciudad1.png"))); // NOI18N
        imagenCiudad4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        imagenCiudad4.setBorderPainted(false);
        imagenCiudad4.setContentAreaFilled(false);
        imagenCiudad4.setFocusable(false);
        imagenCiudad4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imagenCiudad4ActionPerformed(evt);
            }
        });

        lblNombreCiudad4.setText("Ciuda del Fuego");

        lblCoordenadas4.setText("39:87 - Enduos");

        javax.swing.GroupLayout imagenCCiudad4Layout = new javax.swing.GroupLayout(imagenCCiudad4);
        imagenCCiudad4.setLayout(imagenCCiudad4Layout);
        imagenCCiudad4Layout.setHorizontalGroup(
                imagenCCiudad4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(imagenCCiudad4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(imagenCCiudad4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(imagenCiudad4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblNombreCiudad4, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                                        .addComponent(lblCoordenadas4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        imagenCCiudad4Layout.setVerticalGroup(
                imagenCCiudad4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(imagenCCiudad4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(imagenCiudad4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNombreCiudad4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCoordenadas4)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        edificioAcademia.add(imagenCCiudad4, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 169, -1, -1));

        imagenCCiudad5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        imagenCCiudad5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/backg-2-330-260.png"))); // NOI18N

        imagenCiudad5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/ISLA/imagenciudad1.png"))); // NOI18N
        imagenCiudad5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        imagenCiudad5.setBorderPainted(false);
        imagenCiudad5.setContentAreaFilled(false);
        imagenCiudad5.setFocusable(false);
        imagenCiudad5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imagenCiudad5ActionPerformed(evt);
            }
        });

        lblNombreCiudad5.setText("Ciuda del Fuego");

        lblCoordenadas5.setText("39:87 - Enduos");

        javax.swing.GroupLayout imagenCCiudad5Layout = new javax.swing.GroupLayout(imagenCCiudad5);
        imagenCCiudad5.setLayout(imagenCCiudad5Layout);
        imagenCCiudad5Layout.setHorizontalGroup(
                imagenCCiudad5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(imagenCCiudad5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(imagenCCiudad5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(imagenCiudad5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblNombreCiudad5, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                                        .addComponent(lblCoordenadas5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        imagenCCiudad5Layout.setVerticalGroup(
                imagenCCiudad5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(imagenCCiudad5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(imagenCiudad5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNombreCiudad5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCoordenadas5)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        edificioAcademia.add(imagenCCiudad5, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 169, -1, -1));

        imagenCCiudad6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        imagenCCiudad6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/backg-2-330-260.png"))); // NOI18N

        imagenCiudad6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/ISLA/imagenciudad1.png"))); // NOI18N
        imagenCiudad6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        imagenCiudad6.setBorderPainted(false);
        imagenCiudad6.setContentAreaFilled(false);
        imagenCiudad6.setFocusable(false);
        imagenCiudad6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imagenCiudad6ActionPerformed(evt);
            }
        });

        lblNombreCiudad6.setText("Ciuda del Fuego");

        lblCoordenadas6.setText("39:87 - Enduos");

        javax.swing.GroupLayout imagenCCiudad6Layout = new javax.swing.GroupLayout(imagenCCiudad6);
        imagenCCiudad6.setLayout(imagenCCiudad6Layout);
        imagenCCiudad6Layout.setHorizontalGroup(
                imagenCCiudad6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(imagenCCiudad6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(imagenCCiudad6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(imagenCiudad6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblNombreCiudad6, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                                        .addComponent(lblCoordenadas6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        imagenCCiudad6Layout.setVerticalGroup(
                imagenCCiudad6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(imagenCCiudad6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(imagenCiudad6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNombreCiudad6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCoordenadas6)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        edificioAcademia.add(imagenCCiudad6, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 169, -1, -1));

        imagenCCiudad7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        imagenCCiudad7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/backg-2-330-260.png"))); // NOI18N

        imagenCiudad7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/ISLA/imagenciudad1.png"))); // NOI18N
        imagenCiudad7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        imagenCiudad7.setBorderPainted(false);
        imagenCiudad7.setContentAreaFilled(false);
        imagenCiudad7.setFocusable(false);
        imagenCiudad7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imagenCiudad7ActionPerformed(evt);
            }
        });

        lblNombreCiudad7.setText("Ciuda del Fuego");

        lblCoordenadas7.setText("39:87 - Enduos");

        javax.swing.GroupLayout imagenCCiudad7Layout = new javax.swing.GroupLayout(imagenCCiudad7);
        imagenCCiudad7.setLayout(imagenCCiudad7Layout);
        imagenCCiudad7Layout.setHorizontalGroup(
                imagenCCiudad7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(imagenCCiudad7Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(imagenCCiudad7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(imagenCiudad7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblNombreCiudad7, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                                        .addComponent(lblCoordenadas7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        imagenCCiudad7Layout.setVerticalGroup(
                imagenCCiudad7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(imagenCCiudad7Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(imagenCiudad7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNombreCiudad7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCoordenadas7)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        edificioAcademia.add(imagenCCiudad7, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 169, -1, -1));

        panelImage3.add(edificioAcademia, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 12, 510, 330));

        panelVentanaedificio.add(panelImage3, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 11, 530, 350));

        imagenBarcosenventa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        imagenBarcosenventa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/backg-1.png"))); // NOI18N

        cmdComprarbarcomercante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/boton comprar barco mercante.png"))); // NOI18N
        cmdComprarbarcomercante.setBorderPainted(false);
        cmdComprarbarcomercante.setContentAreaFilled(false);
        cmdComprarbarcomercante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdComprarbarcomercanteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout imagenBarcosenventaLayout = new javax.swing.GroupLayout(imagenBarcosenventa);
        imagenBarcosenventa.setLayout(imagenBarcosenventaLayout);
        imagenBarcosenventaLayout.setHorizontalGroup(
                imagenBarcosenventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(imagenBarcosenventaLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(cmdComprarbarcomercante, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(31, Short.MAX_VALUE))
        );
        imagenBarcosenventaLayout.setVerticalGroup(
                imagenBarcosenventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(imagenBarcosenventaLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(cmdComprarbarcomercante)
                                .addContainerGap(14, Short.MAX_VALUE))
        );

        panelVentanaedificio.add(imagenBarcosenventa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 305, 256, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelVentanaedificio, javax.swing.GroupLayout.DEFAULT_SIZE, 816, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelVentanaedificio, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdDestruiredificioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdDestruiredificioActionPerformed
        try {
            this.verpuerto.destruiredificio();
        } catch (SQLException ex) {

        }
    }//GEN-LAST:event_cmdDestruiredificioActionPerformed

    private void cmdElevarniveledificioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdElevarniveledificioActionPerformed
        try {
            this.verpuerto.elevarniveledificio();
        } catch (SQLException ex) {

        }
    }//GEN-LAST:event_cmdElevarniveledificioActionPerformed

    private void imagenCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imagenCiudadActionPerformed
        this.mostrar_enviar_recursos(this.lblNombreCiudad.getText());
    }//GEN-LAST:event_imagenCiudadActionPerformed

    private void imagenCiudad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imagenCiudad1ActionPerformed
        this.mostrar_enviar_recursos(this.lblNombreCiudad1.getText());

    }//GEN-LAST:event_imagenCiudad1ActionPerformed

    private void imagenCiudad2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imagenCiudad2ActionPerformed
        this.mostrar_enviar_recursos(this.lblNombreCiudad2.getText());

    }//GEN-LAST:event_imagenCiudad2ActionPerformed

    private void imagenCiudad3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imagenCiudad3ActionPerformed
        this.mostrar_enviar_recursos(this.lblNombreCiudad3.getText());

    }//GEN-LAST:event_imagenCiudad3ActionPerformed

    private void imagenCiudad4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imagenCiudad4ActionPerformed
        this.mostrar_enviar_recursos(this.lblNombreCiudad4.getText());

    }//GEN-LAST:event_imagenCiudad4ActionPerformed

    private void imagenCiudad5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imagenCiudad5ActionPerformed
        this.mostrar_enviar_recursos(this.lblNombreCiudad5.getText());

    }//GEN-LAST:event_imagenCiudad5ActionPerformed

    private void imagenCiudad6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imagenCiudad6ActionPerformed
        this.mostrar_enviar_recursos(this.lblNombreCiudad6.getText());

    }//GEN-LAST:event_imagenCiudad6ActionPerformed

    private void imagenCiudad7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imagenCiudad7ActionPerformed
        this.mostrar_enviar_recursos(this.lblNombreCiudad7.getText());

    }//GEN-LAST:event_imagenCiudad7ActionPerformed

    private void cmdComprarbarcomercanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdComprarbarcomercanteActionPerformed
        try {
            ComprarBarcoMercante comprarbarco = new ComprarBarcoMercante(this.verpuerto.getVciudad().getCiudad(), this.barcoacomprar);
            comprarbarco.CUComprarBarcomercante();
            ConstruirEdificio.actualizarinterfazgrafica(this.verpuerto.vciudad);
        } catch (SQLException ex) {

        }

    }//GEN-LAST:event_cmdComprarbarcomercanteActionPerformed

    public void mostrar_enviar_recursos(String nombreciudad) {
        Ciudad ciudadllegada = new Ciudad();

        ciudadllegada.setNombre(nombreciudad);
        ciudadllegada.setJugador(this.verpuerto.getVciudad().getCiudad().getJugador());
        VEnviarRecurso venviarrecursos = new VEnviarRecurso(this.verpuerto.getVciudad().getCiudad(), ciudadllegada);
        venviarrecursos.setVciudad(this.verpuerto.vciudad);
        this.hide();
    }

    public JButton getCmdDestruiredificio() {
        return cmdDestruiredificio;
    }

    public JButton getCmdElevarniveledificio() {
        return cmdElevarniveledificio;
    }

    public PanelImage getImagenAzufre() {
        return imagenAzufre;
    }

    public PanelImage getImagenCristal() {
        return imagenCristal;
    }

    public PanelImage getImagenMadera() {
        return imagenMadera;
    }

    public PanelImage getImagenMarmol() {
        return imagenMarmol;
    }

    public JLabel getLblAzufre() {
        return lblAzufre;
    }

    public JLabel getLblCristal() {
        return lblCristal;
    }

    public JLabel getLblMadera() {
        return lblMadera;
    }

    public JLabel getLblMarmol() {
        return lblMarmol;
    }

    public JLabel getLblNivel() {
        return lblNivel;
    }

    public JLabel getLblNivelMaximo() {
        return lblNivelMaximo;
    }

    public PanelImage getImagenCCiudad() {
        return imagenCCiudad;
    }

    public PanelImage getImagenCCiudad1() {
        return imagenCCiudad1;
    }

    public PanelImage getImagenCCiudad2() {
        return imagenCCiudad2;
    }

    public PanelImage getImagenCCiudad3() {
        return imagenCCiudad3;
    }

    public PanelImage getImagenCCiudad4() {
        return imagenCCiudad4;
    }

    public PanelImage getImagenCCiudad5() {
        return imagenCCiudad5;
    }

    public PanelImage getImagenCCiudad6() {
        return imagenCCiudad6;
    }

    public PanelImage getImagenCCiudad7() {
        return imagenCCiudad7;
    }

    public JButton getImagenCiudad() {
        return imagenCiudad;
    }

    public JButton getImagenCiudad1() {
        return imagenCiudad1;
    }

    public JButton getImagenCiudad2() {
        return imagenCiudad2;
    }

    public JButton getImagenCiudad3() {
        return imagenCiudad3;
    }

    public JButton getImagenCiudad4() {
        return imagenCiudad4;
    }

    public JButton getImagenCiudad5() {
        return imagenCiudad5;
    }

    public JButton getImagenCiudad6() {
        return imagenCiudad6;
    }

    public JButton getImagenCiudad7() {
        return imagenCiudad7;
    }

    public JLabel getLblCoordenadas() {
        return lblCoordenadas;
    }

    public JLabel getLblCoordenadas1() {
        return lblCoordenadas1;
    }

    public JLabel getLblCoordenadas2() {
        return lblCoordenadas2;
    }

    public JLabel getLblCoordenadas3() {
        return lblCoordenadas3;
    }

    public JLabel getLblCoordenadas4() {
        return lblCoordenadas4;
    }

    public JLabel getLblCoordenadas5() {
        return lblCoordenadas5;
    }

    public JLabel getLblCoordenadas6() {
        return lblCoordenadas6;
    }

    public JLabel getLblCoordenadas7() {
        return lblCoordenadas7;
    }

    public JLabel getLblNombreCiudad() {
        return lblNombreCiudad;
    }

    public JLabel getLblNombreCiudad1() {
        return lblNombreCiudad1;
    }

    public JLabel getLblNombreCiudad2() {
        return lblNombreCiudad2;
    }

    public JLabel getLblNombreCiudad3() {
        return lblNombreCiudad3;
    }

    public JLabel getLblNombreCiudad4() {
        return lblNombreCiudad4;
    }

    public JLabel getLblNombreCiudad5() {
        return lblNombreCiudad5;
    }

    public JLabel getLblNombreCiudad6() {
        return lblNombreCiudad6;
    }

    public JLabel getLblNombreCiudad7() {
        return lblNombreCiudad7;
    }
    // End of variables declaration//GEN-END:variables
}
