/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jmg.buzios.view.ejercito;

import com.jmg.buzios.BuziosApp;
import com.jmg.buzios.controller.ejercito.DesasignarArmaaUnidad;
import com.jmg.buzios.model.militar.ejercito.Arma;
import com.jmg.buzios.model.militar.ejercito.UnidadMilitar;
import com.jmg.buzios.view.ciudad.VCiudad;
import org.edisoncor.gui.panel.PanelImage;

import javax.swing.*;
import java.sql.SQLException;
import java.util.List;

/**
 * @author Alumno
 */
public class VDesasignarArma extends javax.swing.JFrame {

    /**
     * Creates new form VDesasignarArma
     */

    private VCiudad ciudadjugador;
    private UnidadMilitar unidadmilitar;
    private List<Arma> armas;
    private List<Integer> cantidad;
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdDesasignararma;
    private javax.swing.JButton cmdDesasignararma1;
    private javax.swing.JButton cmdDesasignararma2;
    private javax.swing.JButton cmdDesasignararma3;
    private org.edisoncor.gui.panel.PanelImage imagenArma;
    private org.edisoncor.gui.panel.PanelImage imagenArma1;
    private org.edisoncor.gui.panel.PanelImage imagenArma2;
    private org.edisoncor.gui.panel.PanelImage imagenArma3;
    private org.edisoncor.gui.panel.PanelImage imagenArmasasignadas;
    private javax.swing.JLabel lblArma;
    private javax.swing.JLabel lblArma1;
    private javax.swing.JLabel lblArma2;
    private javax.swing.JLabel lblArma3;
    private javax.swing.JLabel lblCantidadarma;
    private javax.swing.JLabel lblCantidadarma1;
    private javax.swing.JLabel lblCantidadarma2;
    private javax.swing.JLabel lblCantidadarma3;
    private javax.swing.JLabel lblNombredeUnidadMilitar2;
    private javax.swing.JLabel lblSUnidadMilitar;
    private javax.swing.JLabel lblUnidadMilitar;
    private javax.swing.JTextField txtCantidadadesasignar;
    private javax.swing.JTextField txtCantidadadesasignar1;
    private javax.swing.JTextField txtCantidadadesasignar2;
    private javax.swing.JTextField txtCantidadadesasignar3;

    public VDesasignarArma(VCiudad ciudadjugador, UnidadMilitar unidadmilitar, List<Arma> armas, List<Integer> cantidad) {
        initComponents();
        //	 panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/back-3.png"))); // NOI18N

        imagenArmasasignadas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/backg-2.png"))); // NOI18N

        cmdDesasignararma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/Boton Desasignar.png"))); // NOI18N
        cmdDesasignararma1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/Boton Desasignar.png"))); // NOI18N
        cmdDesasignararma2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/Boton Desasignar.png"))); // NOI18N

        cmdDesasignararma3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/Boton Desasignar.png"))); // NOI18N

        this.ciudadjugador = ciudadjugador;
        this.unidadmilitar = unidadmilitar;
        this.armas = armas;
        this.cantidad = cantidad;

        this.setLocationRelativeTo(null);
        this.show();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagenArmasasignadas = new org.edisoncor.gui.panel.PanelImage();
        imagenArma = new org.edisoncor.gui.panel.PanelImage();
        lblArma = new javax.swing.JLabel();
        lblCantidadarma = new javax.swing.JLabel();
        cmdDesasignararma = new javax.swing.JButton();
        txtCantidadadesasignar = new javax.swing.JTextField();
        cmdDesasignararma1 = new javax.swing.JButton();
        txtCantidadadesasignar1 = new javax.swing.JTextField();
        lblCantidadarma1 = new javax.swing.JLabel();
        lblArma1 = new javax.swing.JLabel();
        imagenArma1 = new org.edisoncor.gui.panel.PanelImage();
        cmdDesasignararma2 = new javax.swing.JButton();
        txtCantidadadesasignar2 = new javax.swing.JTextField();
        lblCantidadarma2 = new javax.swing.JLabel();
        lblArma2 = new javax.swing.JLabel();
        imagenArma2 = new org.edisoncor.gui.panel.PanelImage();
        cmdDesasignararma3 = new javax.swing.JButton();
        txtCantidadadesasignar3 = new javax.swing.JTextField();
        lblCantidadarma3 = new javax.swing.JLabel();
        lblArma3 = new javax.swing.JLabel();
        imagenArma3 = new org.edisoncor.gui.panel.PanelImage();
        lblSUnidadMilitar = new javax.swing.JLabel();
        lblUnidadMilitar = new javax.swing.JLabel();
        lblNombredeUnidadMilitar2 = new javax.swing.JLabel();

        imagenArmasasignadas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        imagenArmasasignadas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imagenArma.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout imagenArmaLayout = new javax.swing.GroupLayout(imagenArma);
        imagenArma.setLayout(imagenArmaLayout);
        imagenArmaLayout.setHorizontalGroup(
                imagenArmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
        );
        imagenArmaLayout.setVerticalGroup(
                imagenArmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
        );

        imagenArmasasignadas.add(imagenArma, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 56, 102, -1));

        lblArma.setText("Nombrearma");
        lblArma.setOpaque(true);
        imagenArmasasignadas.add(lblArma, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 164, 102, -1));

        lblCantidadarma.setText("Cantidad");
        lblCantidadarma.setOpaque(true);
        imagenArmasasignadas.add(lblCantidadarma, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 184, 102, -1));

        cmdDesasignararma.setBorderPainted(false);
        cmdDesasignararma.setContentAreaFilled(false);
        cmdDesasignararma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdDesasignararmaActionPerformed(evt);
            }
        });
        imagenArmasasignadas.add(cmdDesasignararma, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 230, 102, 20));

        txtCantidadadesasignar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCantidadadesasignarKeyReleased(evt);
            }
        });
        imagenArmasasignadas.add(txtCantidadadesasignar, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 204, 102, -1));

        cmdDesasignararma1.setBorderPainted(false);
        cmdDesasignararma1.setContentAreaFilled(false);
        cmdDesasignararma1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdDesasignararma1ActionPerformed(evt);
            }
        });
        imagenArmasasignadas.add(cmdDesasignararma1, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 230, 102, 20));

        txtCantidadadesasignar1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCantidadadesasignar1KeyReleased(evt);
            }
        });
        imagenArmasasignadas.add(txtCantidadadesasignar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 204, 102, -1));

        lblCantidadarma1.setText("Cantidad");
        lblCantidadarma1.setOpaque(true);
        imagenArmasasignadas.add(lblCantidadarma1, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 184, 102, -1));

        lblArma1.setText("Nombrearma");
        lblArma1.setOpaque(true);
        imagenArmasasignadas.add(lblArma1, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 164, 102, -1));

        imagenArma1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout imagenArma1Layout = new javax.swing.GroupLayout(imagenArma1);
        imagenArma1.setLayout(imagenArma1Layout);
        imagenArma1Layout.setHorizontalGroup(
                imagenArma1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
        );
        imagenArma1Layout.setVerticalGroup(
                imagenArma1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
        );

        imagenArmasasignadas.add(imagenArma1, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 56, 102, -1));

        cmdDesasignararma2.setBorderPainted(false);
        cmdDesasignararma2.setContentAreaFilled(false);
        cmdDesasignararma2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdDesasignararma2ActionPerformed(evt);
            }
        });
        imagenArmasasignadas.add(cmdDesasignararma2, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 230, 102, 20));

        txtCantidadadesasignar2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCantidadadesasignar2KeyReleased(evt);
            }
        });
        imagenArmasasignadas.add(txtCantidadadesasignar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 204, 102, -1));

        lblCantidadarma2.setText("Cantidad");
        lblCantidadarma2.setOpaque(true);
        imagenArmasasignadas.add(lblCantidadarma2, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 184, 102, -1));

        lblArma2.setText("Nombrearma");
        lblArma2.setOpaque(true);
        imagenArmasasignadas.add(lblArma2, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 164, 102, -1));

        imagenArma2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout imagenArma2Layout = new javax.swing.GroupLayout(imagenArma2);
        imagenArma2.setLayout(imagenArma2Layout);
        imagenArma2Layout.setHorizontalGroup(
                imagenArma2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
        );
        imagenArma2Layout.setVerticalGroup(
                imagenArma2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
        );

        imagenArmasasignadas.add(imagenArma2, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 56, 102, -1));

        cmdDesasignararma3.setBorderPainted(false);
        cmdDesasignararma3.setContentAreaFilled(false);
        cmdDesasignararma3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdDesasignararma3ActionPerformed(evt);
            }
        });
        imagenArmasasignadas.add(cmdDesasignararma3, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 230, 102, 20));

        txtCantidadadesasignar3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCantidadadesasignar3KeyReleased(evt);
            }
        });
        imagenArmasasignadas.add(txtCantidadadesasignar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 204, 102, -1));

        lblCantidadarma3.setText("Cantidad");
        lblCantidadarma3.setOpaque(true);
        imagenArmasasignadas.add(lblCantidadarma3, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 184, 102, -1));

        lblArma3.setText("Nombrearma");
        lblArma3.setOpaque(true);
        imagenArmasasignadas.add(lblArma3, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 164, 102, -1));

        imagenArma3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout imagenArma3Layout = new javax.swing.GroupLayout(imagenArma3);
        imagenArma3.setLayout(imagenArma3Layout);
        imagenArma3Layout.setHorizontalGroup(
                imagenArma3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
        );
        imagenArma3Layout.setVerticalGroup(
                imagenArma3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
        );

        imagenArmasasignadas.add(imagenArma3, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 56, 102, -1));

        lblSUnidadMilitar.setText("Nombre Unidad");
        imagenArmasasignadas.add(lblSUnidadMilitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 102, -1));
        imagenArmasasignadas.add(lblUnidadMilitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 12, 210, -1));

        lblNombredeUnidadMilitar2.setText("Nombre Unidad");
        imagenArmasasignadas.add(lblNombredeUnidadMilitar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 120, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addComponent(imagenArmasasignadas, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addComponent(imagenArmasasignadas, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCantidadadesasignarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadadesasignarKeyReleased
        int numero;
        try {
            numero = Integer.parseInt(this.txtCantidadadesasignar.getText());
            if ((Integer.parseInt(this.txtCantidadadesasignar.getText())) <= (Integer.parseInt(this.lblCantidadarma.getText()))) {
                this.txtCantidadadesasignar.setText(numero + "");
            } else {
                this.txtCantidadadesasignar.setText("");
            }

        } catch (NumberFormatException j) {
            this.txtCantidadadesasignar.setText("");
        }
    }//GEN-LAST:event_txtCantidadadesasignarKeyReleased

    private void txtCantidadadesasignar1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadadesasignar1KeyReleased
        int numero;
        try {
            numero = Integer.parseInt(this.txtCantidadadesasignar1.getText());
            if ((Integer.parseInt(this.txtCantidadadesasignar1.getText())) <= (Integer.parseInt(this.lblCantidadarma1.getText()))) {
                this.txtCantidadadesasignar1.setText(numero + "");
            } else {
                this.txtCantidadadesasignar1.setText("");
            }

        } catch (NumberFormatException j) {
            this.txtCantidadadesasignar1.setText("");
        }
    }//GEN-LAST:event_txtCantidadadesasignar1KeyReleased

    private void txtCantidadadesasignar2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadadesasignar2KeyReleased
        int numero;
        try {
            numero = Integer.parseInt(this.txtCantidadadesasignar2.getText());
            if ((Integer.parseInt(this.txtCantidadadesasignar2.getText())) <= (Integer.parseInt(this.lblCantidadarma2.getText()))) {
                this.txtCantidadadesasignar2.setText(numero + "");
            } else {
                this.txtCantidadadesasignar2.setText("");
            }

        } catch (NumberFormatException j) {
            this.txtCantidadadesasignar2.setText("");
        }
    }//GEN-LAST:event_txtCantidadadesasignar2KeyReleased

    private void txtCantidadadesasignar3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadadesasignar3KeyReleased
        int numero;
        try {
            numero = Integer.parseInt(this.txtCantidadadesasignar3.getText());
            if ((Integer.parseInt(this.txtCantidadadesasignar3.getText())) <= (Integer.parseInt(this.lblCantidadarma3.getText()))) {
                this.txtCantidadadesasignar3.setText(numero + "");
            } else {
                this.txtCantidadadesasignar3.setText("");
            }

        } catch (NumberFormatException j) {
            this.txtCantidadadesasignar3.setText("");
        }
    }

    public VCiudad getCiudadjugador() {
        return ciudadjugador;
    }

    public UnidadMilitar getUnidadmilitar() {
        return unidadmilitar;
    }

    public List<Arma> getArmas() {
        return armas;
    }

    public List<Integer> getCantidad() {
        return cantidad;
    }

    public JButton getCmdDesasignararma() {
        return cmdDesasignararma;
    }

    public JButton getCmdDesasignararma1() {
        return cmdDesasignararma1;
    }

    public JButton getCmdDesasignararma2() {
        return cmdDesasignararma2;
    }

    public JButton getCmdDesasignararma3() {
        return cmdDesasignararma3;
    }

    public PanelImage getImagenArma() {
        return imagenArma;
    }

    public PanelImage getImagenArma1() {
        return imagenArma1;
    }

    public PanelImage getImagenArma2() {
        return imagenArma2;
    }

    public PanelImage getImagenArma3() {
        return imagenArma3;
    }

    public PanelImage getImagenArmasasignadas() {
        return imagenArmasasignadas;
    }

    public JLabel getLblArma() {
        return lblArma;
    }

    public JLabel getLblArma1() {
        return lblArma1;
    }

    public JLabel getLblNombredeUnidadMilitar() {
        return lblNombredeUnidadMilitar2;
    }

    public JLabel getLblArma2() {
        return lblArma2;
    }

    public JLabel getLblArma3() {
        return lblArma3;
    }

    public JLabel getLblCantidadarma() {
        return lblCantidadarma;
    }

    public JLabel getLblCantidadarma1() {
        return lblCantidadarma1;
    }

    public JLabel getLblCantidadarma2() {
        return lblCantidadarma2;
    }

    public JLabel getLblCantidadarma3() {
        return lblCantidadarma3;
    }

    public JLabel getLblSUnidadMilitar() {
        return lblSUnidadMilitar;
    }

    public JLabel getLblUnidadMilitar() {
        return lblUnidadMilitar;
    }

    public JTextField getTxtCantidadadesasignar() {
        return txtCantidadadesasignar;
    }

    public JTextField getTxtCantidadadesasignar1() {
        return txtCantidadadesasignar1;
    }

    public JTextField getTxtCantidadadesasignar2() {
        return txtCantidadadesasignar2;
    }

    public JTextField getTxtCantidadadesasignar3() {
        return txtCantidadadesasignar3;
    }//GEN-LAST:event_txtCantidadadesasignar3KeyReleased

    private void cmdDesasignararmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdDesasignararmaActionPerformed
        if (!"".equals(this.txtCantidadadesasignar.getText())) {
               DesasignarArmaaUnidad desasignar = new DesasignarArmaaUnidad(this.unidadmilitar, this.armas.get(0), Integer.parseInt(this.txtCantidadadesasignar.getText()), this.ciudadjugador);
                desasignar.CUDesasignarArmaaUnidad();
                this.hide();

        }
    }//GEN-LAST:event_cmdDesasignararmaActionPerformed

    private void cmdDesasignararma1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdDesasignararma1ActionPerformed
        if (!"".equals(this.txtCantidadadesasignar1.getText())) {

                DesasignarArmaaUnidad desasignar = new DesasignarArmaaUnidad(this.unidadmilitar, this.armas.get(1), Integer.parseInt(this.txtCantidadadesasignar1.getText()), this.ciudadjugador);
                desasignar.CUDesasignarArmaaUnidad();
                this.hide();

        }
    }//GEN-LAST:event_cmdDesasignararma1ActionPerformed

    private void cmdDesasignararma2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdDesasignararma2ActionPerformed
        if (!"".equals(this.txtCantidadadesasignar2.getText())) {

                DesasignarArmaaUnidad desasignar = new DesasignarArmaaUnidad(this.unidadmilitar, this.armas.get(2), Integer.parseInt(this.txtCantidadadesasignar2.getText()), this.ciudadjugador);
                desasignar.CUDesasignarArmaaUnidad();
                this.hide();

        }
    }//GEN-LAST:event_cmdDesasignararma2ActionPerformed

    private void cmdDesasignararma3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdDesasignararma3ActionPerformed
        if (!"".equals(this.txtCantidadadesasignar3.getText())) {

                DesasignarArmaaUnidad desasignar = new DesasignarArmaaUnidad(this.unidadmilitar, this.armas.get(3), Integer.parseInt(this.txtCantidadadesasignar3.getText()), this.ciudadjugador);
                desasignar.CUDesasignarArmaaUnidad();
                this.hide();

        }
    }//GEN-LAST:event_cmdDesasignararma3ActionPerformed
    // End of variables declaration//GEN-END:variables


}
