/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jmg.buzios.view.ciudad;

import com.jmg.buzios.controller.ciudad.MostrarCiudad;
import com.jmg.buzios.controller.edificio.VerEdificio;
import com.jmg.buzios.controller.isla.MostrarIsla;
import com.jmg.buzios.controller.isla.MostrarMundo;
import com.jmg.buzios.model.ciudad.Ciudad;
import org.edisoncor.gui.panel.PanelImage;

import javax.swing.*;
import java.sql.SQLException;

/**
 * @author Alumno
 */
public class VCiudad extends javax.swing.JFrame {

    private Ciudad ciudad;
    private boolean control = false;
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cboCiudades;
    private javax.swing.JButton cmdEdificio10;
    private javax.swing.JButton cmdEdificio11;
    private javax.swing.JButton cmdEdificio12;
    private javax.swing.JButton cmdEdificio2;
    private javax.swing.JButton cmdEdificio3;
    private javax.swing.JButton cmdEdificio4;
    private javax.swing.JButton cmdEdificio5;
    private javax.swing.JButton cmdEdificio6;
    private javax.swing.JButton cmdEdificio7;
    private javax.swing.JButton cmdEdificio8;
    private javax.swing.JButton cmdEdificio9;
    private javax.swing.JButton cmdEdificioIntendencia;
    private javax.swing.JButton cmdEdificioNaval;
    private javax.swing.JButton cmdEdificioNaval1;
    private javax.swing.JButton cmdMuro;
    private javax.swing.JButton cmdVerIsla;
    private javax.swing.JButton cmdVerMensajes;
    private javax.swing.JButton cmdVerMundo;
    private org.edisoncor.gui.panel.PanelImage imagenCiudad;
    private org.edisoncor.gui.panel.PanelImage imagenFondoJuego;
    private org.edisoncor.gui.panel.PanelImage imagenMadera;
    private org.edisoncor.gui.panel.PanelImage imagenMadera2;
    private org.edisoncor.gui.panel.PanelImage imagenMadera3;
    private org.edisoncor.gui.panel.PanelImage imagenMadera4;
    private org.edisoncor.gui.panel.PanelImage imagenMadera7;
    private org.edisoncor.gui.panel.PanelImage imagenVino;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblAzufre;
    private javax.swing.JLabel lblCiudades;
    private javax.swing.JLabel lblCristal;
    private javax.swing.JLabel lblMadera;
    private javax.swing.JLabel lblMarmol;
    private javax.swing.JLabel lblOro;
    private javax.swing.JLabel lblVino;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private org.edisoncor.gui.panel.PanelImage panelImage2;
    private org.edisoncor.gui.panel.PanelImage panelImage3;

    public VCiudad(Ciudad ciudad) {
        initComponents();
        this.ciudad = ciudad;
        this.setLocationRelativeTo(null);
        this.show();


    }

    public void setControl(boolean control) {
        this.control = control;
    }

    public Ciudad getCiudad() {
        return ciudad;
    }

    public void setCiudad(Ciudad ciudad) {
        this.ciudad = ciudad;
    }

    public JComboBox getCboCiudades() {
        return cboCiudades;
    }

    public void setCboCiudades(JComboBox cboCiudades) {
        this.cboCiudades = cboCiudades;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagenFondoJuego = new org.edisoncor.gui.panel.PanelImage();
        imagenCiudad = new org.edisoncor.gui.panel.PanelImage();
        cmdMuro = new javax.swing.JButton();
        cmdEdificioNaval = new javax.swing.JButton();
        cmdEdificioNaval1 = new javax.swing.JButton();
        cmdEdificioIntendencia = new javax.swing.JButton();
        cmdEdificio2 = new javax.swing.JButton();
        cmdEdificio3 = new javax.swing.JButton();
        cmdEdificio4 = new javax.swing.JButton();
        cmdEdificio5 = new javax.swing.JButton();
        cmdEdificio6 = new javax.swing.JButton();
        cmdEdificio7 = new javax.swing.JButton();
        cmdEdificio8 = new javax.swing.JButton();
        cmdEdificio9 = new javax.swing.JButton();
        cmdEdificio10 = new javax.swing.JButton();
        cmdEdificio11 = new javax.swing.JButton();
        cmdEdificio12 = new javax.swing.JButton();
        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        cboCiudades = new javax.swing.JComboBox();
        lblCiudades = new javax.swing.JLabel();
        cmdVerMensajes = new javax.swing.JButton();
        cmdVerIsla = new javax.swing.JButton();
        cmdVerMundo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        panelImage2 = new org.edisoncor.gui.panel.PanelImage();
        imagenMadera = new org.edisoncor.gui.panel.PanelImage();
        lblMadera = new javax.swing.JLabel();
        imagenVino = new org.edisoncor.gui.panel.PanelImage();
        lblVino = new javax.swing.JLabel();
        imagenMadera2 = new org.edisoncor.gui.panel.PanelImage();
        lblMarmol = new javax.swing.JLabel();
        imagenMadera3 = new org.edisoncor.gui.panel.PanelImage();
        lblCristal = new javax.swing.JLabel();
        imagenMadera4 = new org.edisoncor.gui.panel.PanelImage();
        lblAzufre = new javax.swing.JLabel();
        panelImage3 = new org.edisoncor.gui.panel.PanelImage();
        lblOro = new javax.swing.JLabel();
        imagenMadera7 = new org.edisoncor.gui.panel.PanelImage();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CIUDAD");

        imagenFondoJuego.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        imagenFondoJuego.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/backg-1.png"))); // NOI18N
        imagenFondoJuego.setLayout(null);

        imagenCiudad.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        imagenCiudad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/imagenciudadvacia.jpg"))); // NOI18N
        imagenCiudad.setLayout(null);

        cmdMuro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cmdMuro.setBorderPainted(false);
        cmdMuro.setContentAreaFilled(false);
        cmdMuro.setDefaultCapable(false);
        cmdMuro.setEnabled(false);
        cmdMuro.setFocusPainted(false);
        cmdMuro.setFocusable(false);
        cmdMuro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMuroActionPerformed(evt);
            }
        });
        imagenCiudad.add(cmdMuro);
        cmdMuro.setBounds(420, 0, 70, 80);

        cmdEdificioNaval.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cmdEdificioNaval.setBorderPainted(false);
        cmdEdificioNaval.setContentAreaFilled(false);
        cmdEdificioNaval.setDefaultCapable(false);
        cmdEdificioNaval.setFocusPainted(false);
        cmdEdificioNaval.setFocusable(false);
        cmdEdificioNaval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEdificioNavalActionPerformed(evt);
            }
        });
        imagenCiudad.add(cmdEdificioNaval);
        cmdEdificioNaval.setBounds(180, 340, 150, 120);

        cmdEdificioNaval1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cmdEdificioNaval1.setBorderPainted(false);
        cmdEdificioNaval1.setContentAreaFilled(false);
        cmdEdificioNaval1.setDefaultCapable(false);
        cmdEdificioNaval1.setFocusPainted(false);
        cmdEdificioNaval1.setFocusable(false);
        cmdEdificioNaval1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEdificioNaval1ActionPerformed(evt);
            }
        });
        imagenCiudad.add(cmdEdificioNaval1);
        cmdEdificioNaval1.setBounds(430, 340, 150, 120);

        cmdEdificioIntendencia.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alumno\\Desktop\\ASyRC - 7 y Anexos\\EdificiosBasicos\\edificioacademias.png")); // NOI18N
        cmdEdificioIntendencia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cmdEdificioIntendencia.setBorderPainted(false);
        cmdEdificioIntendencia.setContentAreaFilled(false);
        cmdEdificioIntendencia.setDefaultCapable(false);
        cmdEdificioIntendencia.setFocusPainted(false);
        cmdEdificioIntendencia.setFocusable(false);
        cmdEdificioIntendencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEdificioIntendenciaActionPerformed(evt);
            }
        });
        imagenCiudad.add(cmdEdificioIntendencia);
        cmdEdificioIntendencia.setBounds(290, 140, 80, 90);

        cmdEdificio2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alumno\\Desktop\\ASyRC - 7 y Anexos\\EdificiosBasicos\\edificioacademias.png")); // NOI18N
        cmdEdificio2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cmdEdificio2.setBorderPainted(false);
        cmdEdificio2.setContentAreaFilled(false);
        cmdEdificio2.setDefaultCapable(false);
        cmdEdificio2.setFocusPainted(false);
        cmdEdificio2.setFocusable(false);
        cmdEdificio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEdificio2ActionPerformed(evt);
            }
        });
        imagenCiudad.add(cmdEdificio2);
        cmdEdificio2.setBounds(20, 200, 70, 80);

        cmdEdificio3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alumno\\Desktop\\ASyRC - 7 y Anexos\\EdificiosBasicos\\edificioacademias.png")); // NOI18N
        cmdEdificio3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cmdEdificio3.setBorderPainted(false);
        cmdEdificio3.setContentAreaFilled(false);
        cmdEdificio3.setDefaultCapable(false);
        cmdEdificio3.setFocusPainted(false);
        cmdEdificio3.setFocusable(false);
        cmdEdificio3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEdificio3ActionPerformed(evt);
            }
        });
        imagenCiudad.add(cmdEdificio3);
        cmdEdificio3.setBounds(120, 240, 70, 80);

        cmdEdificio4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alumno\\Desktop\\ASyRC - 7 y Anexos\\EdificiosBasicos\\edificioacademias.png")); // NOI18N
        cmdEdificio4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cmdEdificio4.setBorderPainted(false);
        cmdEdificio4.setContentAreaFilled(false);
        cmdEdificio4.setDefaultCapable(false);
        cmdEdificio4.setFocusPainted(false);
        cmdEdificio4.setFocusable(false);
        cmdEdificio4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEdificio4ActionPerformed(evt);
            }
        });
        imagenCiudad.add(cmdEdificio4);
        cmdEdificio4.setBounds(190, 170, 70, 80);

        cmdEdificio5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/EDIFICIOSCIUDAD/parcelavacia.png"))); // NOI18N
        cmdEdificio5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cmdEdificio5.setBorderPainted(false);
        cmdEdificio5.setContentAreaFilled(false);
        cmdEdificio5.setDefaultCapable(false);
        cmdEdificio5.setFocusPainted(false);
        cmdEdificio5.setFocusable(false);
        cmdEdificio5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEdificio5ActionPerformed(evt);
            }
        });
        imagenCiudad.add(cmdEdificio5);
        cmdEdificio5.setBounds(70, 120, 70, 80);

        cmdEdificio6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alumno\\Desktop\\ASyRC - 7 y Anexos\\EdificiosBasicos\\edificiocabañaguardabosque.png")); // NOI18N
        cmdEdificio6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cmdEdificio6.setBorderPainted(false);
        cmdEdificio6.setContentAreaFilled(false);
        cmdEdificio6.setDefaultCapable(false);
        cmdEdificio6.setFocusPainted(false);
        cmdEdificio6.setFocusable(false);
        cmdEdificio6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEdificio6ActionPerformed(evt);
            }
        });
        imagenCiudad.add(cmdEdificio6);
        cmdEdificio6.setBounds(210, 50, 70, 80);

        cmdEdificio7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alumno\\Desktop\\ASyRC - 7 y Anexos\\EdificiosBasicos\\edificioacademias.png")); // NOI18N
        cmdEdificio7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cmdEdificio7.setBorderPainted(false);
        cmdEdificio7.setContentAreaFilled(false);
        cmdEdificio7.setDefaultCapable(false);
        cmdEdificio7.setFocusPainted(false);
        cmdEdificio7.setFocusable(false);
        cmdEdificio7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEdificio7ActionPerformed(evt);
            }
        });
        imagenCiudad.add(cmdEdificio7);
        cmdEdificio7.setBounds(310, 40, 70, 80);

        cmdEdificio8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alumno\\Desktop\\ASyRC - 7 y Anexos\\EdificiosBasicos\\edificioacademias.png")); // NOI18N
        cmdEdificio8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cmdEdificio8.setBorderPainted(false);
        cmdEdificio8.setContentAreaFilled(false);
        cmdEdificio8.setDefaultCapable(false);
        cmdEdificio8.setFocusPainted(false);
        cmdEdificio8.setFocusable(false);
        cmdEdificio8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEdificio8ActionPerformed(evt);
            }
        });
        imagenCiudad.add(cmdEdificio8);
        cmdEdificio8.setBounds(390, 110, 70, 80);

        cmdEdificio9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alumno\\Desktop\\ASyRC - 7 y Anexos\\EdificiosBasicos\\edificioacademias.png")); // NOI18N
        cmdEdificio9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cmdEdificio9.setBorderPainted(false);
        cmdEdificio9.setContentAreaFilled(false);
        cmdEdificio9.setDefaultCapable(false);
        cmdEdificio9.setFocusPainted(false);
        cmdEdificio9.setFocusable(false);
        cmdEdificio9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEdificio9ActionPerformed(evt);
            }
        });
        imagenCiudad.add(cmdEdificio9);
        cmdEdificio9.setBounds(480, 90, 70, 80);

        cmdEdificio10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alumno\\Desktop\\ASyRC - 7 y Anexos\\EdificiosBasicos\\edificioalmacen.png")); // NOI18N
        cmdEdificio10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cmdEdificio10.setBorderPainted(false);
        cmdEdificio10.setContentAreaFilled(false);
        cmdEdificio10.setDefaultCapable(false);
        cmdEdificio10.setFocusPainted(false);
        cmdEdificio10.setFocusable(false);
        cmdEdificio10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEdificio10ActionPerformed(evt);
            }
        });
        imagenCiudad.add(cmdEdificio10);
        cmdEdificio10.setBounds(400, 240, 70, 80);

        cmdEdificio11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alumno\\Desktop\\ASyRC - 7 y Anexos\\EdificiosBasicos\\edificioacademias.png")); // NOI18N
        cmdEdificio11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cmdEdificio11.setBorderPainted(false);
        cmdEdificio11.setContentAreaFilled(false);
        cmdEdificio11.setDefaultCapable(false);
        cmdEdificio11.setFocusPainted(false);
        cmdEdificio11.setFocusable(false);
        cmdEdificio11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEdificio11ActionPerformed(evt);
            }
        });
        imagenCiudad.add(cmdEdificio11);
        cmdEdificio11.setBounds(510, 240, 70, 80);

        cmdEdificio12.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alumno\\Desktop\\ASyRC - 7 y Anexos\\EdificiosBasicos\\edificioalmacen.png")); // NOI18N
        cmdEdificio12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cmdEdificio12.setBorderPainted(false);
        cmdEdificio12.setContentAreaFilled(false);
        cmdEdificio12.setDefaultCapable(false);
        cmdEdificio12.setFocusPainted(false);
        cmdEdificio12.setFocusable(false);
        cmdEdificio12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEdificio12ActionPerformed(evt);
            }
        });
        imagenCiudad.add(cmdEdificio12);
        cmdEdificio12.setBounds(270, 260, 70, 80);

        imagenFondoJuego.add(imagenCiudad);
        imagenCiudad.setBounds(190, 60, 600, 460);

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/backg-1.png"))); // NOI18N

        cboCiudades.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboCiudadesItemStateChanged(evt);
            }
        });
        cboCiudades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCiudadesActionPerformed(evt);
            }
        });

        lblCiudades.setText("Ciudades de Imperio");

        cmdVerMensajes.setText("Ver Mensajes");
        cmdVerMensajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdVerMensajesActionPerformed(evt);
            }
        });

        cmdVerIsla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/mostrar isla.png"))); // NOI18N
        cmdVerIsla.setBorderPainted(false);
        cmdVerIsla.setContentAreaFilled(false);
        cmdVerIsla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdVerIslaActionPerformed(evt);
            }
        });

        cmdVerMundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/mostrar mundo.png"))); // NOI18N
        cmdVerMundo.setBorderPainted(false);
        cmdVerMundo.setContentAreaFilled(false);
        cmdVerMundo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdVerMundoActionPerformed(evt);
            }
        });

        jButton1.setText("Configurar Cuenta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
                panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelImage1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblCiudades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(panelImage1Layout.createSequentialGroup()
                                                .addComponent(cmdVerIsla, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                                .addComponent(cmdVerMundo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(panelImage1Layout.createSequentialGroup()
                                                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                .addComponent(cboCiudades, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(cmdVerMensajes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE))
                                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        panelImage1Layout.setVerticalGroup(
                panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelImage1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblCiudades)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboCiudades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmdVerMensajes, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cmdVerIsla, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cmdVerMundo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 254, Short.MAX_VALUE)
                                .addComponent(jButton1))
        );

        imagenFondoJuego.add(panelImage1);
        panelImage1.setBounds(0, 60, 190, 460);

        panelImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/backg-1.png"))); // NOI18N

        imagenMadera.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        imagenMadera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/Maderadeedificionivel.jpg"))); // NOI18N

        javax.swing.GroupLayout imagenMaderaLayout = new javax.swing.GroupLayout(imagenMadera);
        imagenMadera.setLayout(imagenMaderaLayout);
        imagenMaderaLayout.setHorizontalGroup(
                imagenMaderaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 38, Short.MAX_VALUE)
        );
        imagenMaderaLayout.setVerticalGroup(
                imagenMaderaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );

        lblMadera.setText("1000000");

        imagenVino.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        imagenVino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/VinoImg.png"))); // NOI18N

        javax.swing.GroupLayout imagenVinoLayout = new javax.swing.GroupLayout(imagenVino);
        imagenVino.setLayout(imagenVinoLayout);
        imagenVinoLayout.setHorizontalGroup(
                imagenVinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 38, Short.MAX_VALUE)
        );
        imagenVinoLayout.setVerticalGroup(
                imagenVinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );

        lblVino.setText("1000000");

        imagenMadera2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        imagenMadera2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/Marmoldeedificionivel.jpg"))); // NOI18N

        javax.swing.GroupLayout imagenMadera2Layout = new javax.swing.GroupLayout(imagenMadera2);
        imagenMadera2.setLayout(imagenMadera2Layout);
        imagenMadera2Layout.setHorizontalGroup(
                imagenMadera2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 38, Short.MAX_VALUE)
        );
        imagenMadera2Layout.setVerticalGroup(
                imagenMadera2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );

        lblMarmol.setText("1000000");

        imagenMadera3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        imagenMadera3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/Cristaldeedificionivel.jpg"))); // NOI18N

        javax.swing.GroupLayout imagenMadera3Layout = new javax.swing.GroupLayout(imagenMadera3);
        imagenMadera3.setLayout(imagenMadera3Layout);
        imagenMadera3Layout.setHorizontalGroup(
                imagenMadera3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 38, Short.MAX_VALUE)
        );
        imagenMadera3Layout.setVerticalGroup(
                imagenMadera3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );

        lblCristal.setText("1000000");

        imagenMadera4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        imagenMadera4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/Azufredeedificionivel.jpg"))); // NOI18N

        javax.swing.GroupLayout imagenMadera4Layout = new javax.swing.GroupLayout(imagenMadera4);
        imagenMadera4.setLayout(imagenMadera4Layout);
        imagenMadera4Layout.setHorizontalGroup(
                imagenMadera4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 38, Short.MAX_VALUE)
        );
        imagenMadera4Layout.setVerticalGroup(
                imagenMadera4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );

        lblAzufre.setText("1000000");

        javax.swing.GroupLayout panelImage2Layout = new javax.swing.GroupLayout(panelImage2);
        panelImage2.setLayout(panelImage2Layout);
        panelImage2Layout.setHorizontalGroup(
                panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelImage2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(imagenMadera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMadera, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(imagenVino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblVino, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(imagenMadera2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMarmol, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(imagenMadera3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCristal, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(imagenMadera4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblAzufre, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(90, Short.MAX_VALUE))
        );
        panelImage2Layout.setVerticalGroup(
                panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImage2Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(imagenMadera4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblAzufre, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(imagenMadera3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblCristal, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(imagenMadera2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblMarmol, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(imagenVino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(lblVino, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(imagenMadera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(lblMadera, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap())
        );

        imagenFondoJuego.add(panelImage2);
        panelImage2.setBounds(190, 0, 600, 60);

        panelImage3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/backg-1.png"))); // NOI18N

        lblOro.setText("1000000");

        imagenMadera7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        imagenMadera7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/oro.png"))); // NOI18N

        javax.swing.GroupLayout imagenMadera7Layout = new javax.swing.GroupLayout(imagenMadera7);
        imagenMadera7.setLayout(imagenMadera7Layout);
        imagenMadera7Layout.setHorizontalGroup(
                imagenMadera7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 38, Short.MAX_VALUE)
        );
        imagenMadera7Layout.setVerticalGroup(
                imagenMadera7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelImage3Layout = new javax.swing.GroupLayout(panelImage3);
        panelImage3.setLayout(panelImage3Layout);
        panelImage3Layout.setHorizontalGroup(
                panelImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelImage3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(imagenMadera7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblOro, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(24, Short.MAX_VALUE))
        );
        panelImage3Layout.setVerticalGroup(
                panelImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImage3Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panelImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(imagenMadera7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblOro, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
        );

        imagenFondoJuego.add(panelImage3);
        panelImage3.setBounds(0, 0, 190, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(imagenFondoJuego, javax.swing.GroupLayout.DEFAULT_SIZE, 803, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(imagenFondoJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdMuroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMuroActionPerformed
        try {
            VerEdificio veredificio = new VerEdificio(this.ciudad, this, 1);
            veredificio.CUveredificio();
        } catch (SQLException ex) {

        }
    }//GEN-LAST:event_cmdMuroActionPerformed

    private void cmdEdificioNavalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEdificioNavalActionPerformed
        try {
            VerEdificio veredificio = new VerEdificio(this.ciudad, this, 2);
            veredificio.CUveredificio();
        } catch (SQLException ex) {

        }
    }//GEN-LAST:event_cmdEdificioNavalActionPerformed

    private void cmdEdificioNaval1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEdificioNaval1ActionPerformed
        VerEdificio veredificio = new VerEdificio(this.ciudad, this, 3);
        try {
            veredificio.CUveredificio();
        } catch (SQLException ex) {

        }
    }//GEN-LAST:event_cmdEdificioNaval1ActionPerformed

    private void cmdEdificioIntendenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEdificioIntendenciaActionPerformed
        VerEdificio veredificio = new VerEdificio(this.ciudad, this, 4);
        try {
            veredificio.CUveredificio();
        } catch (SQLException ex) {

        }
    }//GEN-LAST:event_cmdEdificioIntendenciaActionPerformed

    private void cmdEdificio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEdificio2ActionPerformed
        try {
            VerEdificio veredificio = new VerEdificio(this.ciudad, this, 5);
            veredificio.CUveredificio();
        } catch (SQLException ex) {

        }
    }//GEN-LAST:event_cmdEdificio2ActionPerformed

    private void cmdEdificio3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEdificio3ActionPerformed
        try {
            VerEdificio veredificio = new VerEdificio(this.ciudad, this, 6);
            veredificio.CUveredificio();
        } catch (SQLException ex) {

        }
    }//GEN-LAST:event_cmdEdificio3ActionPerformed

    private void cmdEdificio4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEdificio4ActionPerformed
        try {
            VerEdificio veredificio = new VerEdificio(this.ciudad, this, 7);
            veredificio.CUveredificio();
        } catch (SQLException ex) {

        }
    }//GEN-LAST:event_cmdEdificio4ActionPerformed

    private void cmdEdificio5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEdificio5ActionPerformed
        try {
            VerEdificio veredificio = new VerEdificio(this.ciudad, this, 8);
            veredificio.CUveredificio();
        } catch (SQLException ex) {

        }
    }//GEN-LAST:event_cmdEdificio5ActionPerformed

    private void cmdEdificio6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEdificio6ActionPerformed
        try {
            VerEdificio veredificio = new VerEdificio(this.ciudad, this, 9);
            veredificio.CUveredificio();
        } catch (SQLException ex) {

        }
    }//GEN-LAST:event_cmdEdificio6ActionPerformed

    private void cmdEdificio7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEdificio7ActionPerformed
        try {
            VerEdificio veredificio = new VerEdificio(this.ciudad, this, 10);
            veredificio.CUveredificio();
        } catch (SQLException ex) {

        }
    }//GEN-LAST:event_cmdEdificio7ActionPerformed

    private void cmdEdificio8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEdificio8ActionPerformed
        try {
            VerEdificio veredificio = new VerEdificio(this.ciudad, this, 11);
            veredificio.CUveredificio();
        } catch (SQLException ex) {

        }
    }//GEN-LAST:event_cmdEdificio8ActionPerformed

    private void cmdEdificio9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEdificio9ActionPerformed
        try {
            VerEdificio veredificio = new VerEdificio(this.ciudad, this, 12);
            veredificio.CUveredificio();
        } catch (SQLException ex) {

        }
    }//GEN-LAST:event_cmdEdificio9ActionPerformed

    private void cmdEdificio10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEdificio10ActionPerformed
        try {
            VerEdificio veredificio = new VerEdificio(this.ciudad, this, 13);
            veredificio.CUveredificio();
        } catch (SQLException ex) {

        }
    }//GEN-LAST:event_cmdEdificio10ActionPerformed

    private void cmdEdificio11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEdificio11ActionPerformed
        try {
            VerEdificio veredificio = new VerEdificio(this.ciudad, this, 14);
            veredificio.CUveredificio();
        } catch (SQLException ex) {

        }
    }//GEN-LAST:event_cmdEdificio11ActionPerformed

    private void cmdEdificio12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEdificio12ActionPerformed
        try {
            VerEdificio veredificio = new VerEdificio(this.ciudad, this, 15);
            veredificio.CUveredificio();
        } catch (SQLException ex) {

        }
    }

    public JButton getCmdEdificio10() {
        return cmdEdificio10;
    }

    public JButton getCmdEdificio11() {
        return cmdEdificio11;
    }

    public JButton getCmdEdificio12() {
        return cmdEdificio12;
    }

    public JButton getCmdEdificio2() {
        return cmdEdificio2;
    }

    public JButton getCmdEdificio3() {
        return cmdEdificio3;
    }

    public JButton getCmdEdificio4() {
        return cmdEdificio4;
    }

    public JButton getCmdEdificio5() {
        return cmdEdificio5;
    }

    public JButton getCmdEdificio6() {
        return cmdEdificio6;
    }

    public JButton getCmdEdificio7() {
        return cmdEdificio7;
    }

    public JButton getCmdEdificio8() {
        return cmdEdificio8;
    }

    public JButton getCmdEdificio9() {
        return cmdEdificio9;
    }

    public JButton getCmdEdificioIntendencia() {
        return cmdEdificioIntendencia;
    }

    public JButton getCmdEdificioNaval() {
        return cmdEdificioNaval;
    }

    public JButton getCmdEdificioNaval1() {
        return cmdEdificioNaval1;
    }

    public JButton getCmdMuro() {
        return cmdMuro;
    }

    public PanelImage getImagenCiudad() {
        return imagenCiudad;
    }//GEN-LAST:event_cmdEdificio12ActionPerformed

    private void cboCiudadesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboCiudadesItemStateChanged
        if (control) {
            try {

                MostrarCiudad mostrarciudad = new MostrarCiudad(new Ciudad((String) this.cboCiudades.getSelectedItem(), this.ciudad.getJugador()));


                this.control = false;
                mostrarciudad.CUmostrarciudad();
                this.hide();

            } catch (SQLException ex) {

            }
        }

    }//GEN-LAST:event_cboCiudadesItemStateChanged

    private void cboCiudadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCiudadesActionPerformed


    }//GEN-LAST:event_cboCiudadesActionPerformed

    private void cmdVerMundoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdVerMundoActionPerformed
        MostrarMundo vermundo = new MostrarMundo(this.ciudad);
        vermundo.parteMundo = 1;
        vermundo.CUMostrarmundo();
        this.hide();
    }//GEN-LAST:event_cmdVerMundoActionPerformed

    private void cmdVerIslaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdVerIslaActionPerformed
        MostrarIsla mostrarisla = new MostrarIsla(this.ciudad.getIsla(), this.ciudad);
        mostrarisla.CUmostrarisla();
        this.hide();
    }//GEN-LAST:event_cmdVerIslaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        VConfigurarCuenta vconfigurar = new VConfigurarCuenta(this.ciudad.getJugador());

    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmdVerMensajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdVerMensajesActionPerformed
        VVerMensajesRecibidos mensajes = new VVerMensajesRecibidos(this.ciudad);

    }//GEN-LAST:event_cmdVerMensajesActionPerformed

    public JLabel getLblAzufre() {
        return lblAzufre;
    }

    public JLabel getLblCristal() {
        return lblCristal;
    }

    public JLabel getLblMadera() {
        return lblMadera;
    }

    public JLabel getLblMarmol() {
        return lblMarmol;
    }

    public JLabel getLblOro() {
        return lblOro;
    }

    public JLabel getLblVino() {
        return lblVino;
    }
    // End of variables declaration//GEN-END:variables


}
