/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jmg.buzios.view.islas;

import com.jmg.buzios.controller.isla.AsignarTrabajadores;
import com.jmg.buzios.model.ciudad.Ciudad;
import com.jmg.buzios.model.isla.Isla;
import org.edisoncor.gui.panel.PanelImage;

import javax.swing.*;
import java.sql.SQLException;

/**
 * @author Alumno
 */
public class VRecolectarRecurso extends javax.swing.JFrame {


    private String recurso;
    private Ciudad ciudadjugador;/*seguir desde aca*/
    private Isla isla;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider barraTrabajadores;
    private javax.swing.JButton cmdAsignartrabajadores;
    private org.edisoncor.gui.panel.PanelImage imagenHabitante;
    private org.edisoncor.gui.panel.PanelImage imagenLugar;
    private org.edisoncor.gui.panel.PanelImage imagenTrabajador;
    private org.edisoncor.gui.panel.PanelImage imagenfondo1;
    private org.edisoncor.gui.panel.PanelImage imagenfondo2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAsignartrabajadores;
    private javax.swing.JLabel lblCantidadhabitante;
    private javax.swing.JLabel lblCantidadtrabajdor;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private javax.swing.JTextField txtCantidadTrabajadores;
    private javax.swing.JTextPane txtDescripcionlugarrecurso;

    /**
     * Creates new form VRECOLECTARRECURSO
     */


    public VRecolectarRecurso(Isla isla, String recurso, Ciudad ciudadjugador) {
        this.isla = isla;
        this.ciudadjugador = ciudadjugador;


        this.recurso = recurso;
        initComponents();
        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/back-3.png"))); // NOI18N

        imagenfondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/backg-1.png"))); // NOI18N

        imagenfondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/backg-1.png"))); // NOI18N

        this.inicializarimagenrecurso();

        this.setLocationRelativeTo(null);
        this.show();

    }

    private void inicializarimagenrecurso() {

        String ii = ("/IMAGEN/ISLA/" + "Madera" + ".jpg");
        ImageIcon a = new ImageIcon(getClass().getResource(ii));

        this.imagenLugar.setIcon(a);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        imagenfondo1 = new org.edisoncor.gui.panel.PanelImage();
        imagenLugar = new org.edisoncor.gui.panel.PanelImage();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescripcionlugarrecurso = new javax.swing.JTextPane();
        imagenfondo2 = new org.edisoncor.gui.panel.PanelImage();
        imagenHabitante = new org.edisoncor.gui.panel.PanelImage();
        imagenTrabajador = new org.edisoncor.gui.panel.PanelImage();
        lblCantidadhabitante = new javax.swing.JLabel();
        lblCantidadtrabajdor = new javax.swing.JLabel();
        cmdAsignartrabajadores = new javax.swing.JButton();
        lblAsignartrabajadores = new javax.swing.JLabel();
        barraTrabajadores = new javax.swing.JSlider();
        txtCantidadTrabajadores = new javax.swing.JTextField();

        panelImage1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imagenfondo1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        imagenLugar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout imagenLugarLayout = new javax.swing.GroupLayout(imagenLugar);
        imagenLugar.setLayout(imagenLugarLayout);
        imagenLugarLayout.setHorizontalGroup(
                imagenLugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 191, Short.MAX_VALUE)
        );
        imagenLugarLayout.setVerticalGroup(
                imagenLugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 94, Short.MAX_VALUE)
        );

        txtDescripcionlugarrecurso.setEditable(false);
        jScrollPane2.setViewportView(txtDescripcionlugarrecurso);

        javax.swing.GroupLayout imagenfondo1Layout = new javax.swing.GroupLayout(imagenfondo1);
        imagenfondo1.setLayout(imagenfondo1Layout);
        imagenfondo1Layout.setHorizontalGroup(
                imagenfondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(imagenfondo1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(imagenLugar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19))
        );
        imagenfondo1Layout.setVerticalGroup(
                imagenfondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(imagenfondo1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(imagenfondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane2)
                                        .addComponent(imagenLugar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelImage1.add(imagenfondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 19, 537, -1));

        imagenfondo2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        imagenHabitante.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        imagenHabitante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/aldeanoRECOR.png"))); // NOI18N

        javax.swing.GroupLayout imagenHabitanteLayout = new javax.swing.GroupLayout(imagenHabitante);
        imagenHabitante.setLayout(imagenHabitanteLayout);
        imagenHabitanteLayout.setHorizontalGroup(
                imagenHabitanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
        );
        imagenHabitanteLayout.setVerticalGroup(
                imagenHabitanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
        );

        imagenTrabajador.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        imagenTrabajador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/imagen_trabajador.gif"))); // NOI18N

        javax.swing.GroupLayout imagenTrabajadorLayout = new javax.swing.GroupLayout(imagenTrabajador);
        imagenTrabajador.setLayout(imagenTrabajadorLayout);
        imagenTrabajadorLayout.setHorizontalGroup(
                imagenTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
        );
        imagenTrabajadorLayout.setVerticalGroup(
                imagenTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
        );

        lblCantidadhabitante.setText("0");

        lblCantidadtrabajdor.setText("0");

        cmdAsignartrabajadores.setText("Asignar Trabajadores");
        cmdAsignartrabajadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAsignartrabajadoresActionPerformed(evt);
            }
        });

        lblAsignartrabajadores.setText("Trabajadores de Isla");

        barraTrabajadores.setSnapToTicks(true);
        barraTrabajadores.setValue(0);
        barraTrabajadores.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                barraTrabajadoresStateChanged(evt);
            }
        });

        txtCantidadTrabajadores.setEditable(false);
        txtCantidadTrabajadores.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCantidadTrabajadoresKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout imagenfondo2Layout = new javax.swing.GroupLayout(imagenfondo2);
        imagenfondo2.setLayout(imagenfondo2Layout);
        imagenfondo2Layout.setHorizontalGroup(
                imagenfondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(imagenfondo2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(imagenfondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(imagenfondo2Layout.createSequentialGroup()
                                                .addComponent(imagenHabitante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(imagenfondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(imagenfondo2Layout.createSequentialGroup()
                                                                .addGap(80, 80, 80)
                                                                .addComponent(lblAsignartrabajadores, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(imagenfondo2Layout.createSequentialGroup()
                                                                .addGap(73, 73, 73)
                                                                .addComponent(cmdAsignartrabajadores))
                                                        .addGroup(imagenfondo2Layout.createSequentialGroup()
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(barraTrabajadores, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(txtCantidadTrabajadores, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(10, 10, 10)
                                                .addComponent(imagenTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(imagenfondo2Layout.createSequentialGroup()
                                                .addComponent(lblCantidadhabitante, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblCantidadtrabajdor, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
        );
        imagenfondo2Layout.setVerticalGroup(
                imagenfondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(imagenfondo2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(imagenfondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imagenfondo2Layout.createSequentialGroup()
                                                .addComponent(lblAsignartrabajadores)
                                                .addGap(11, 11, 11)
                                                .addGroup(imagenfondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(barraTrabajadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtCantidadTrabajadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(cmdAsignartrabajadores)
                                                .addGap(3, 3, 3))
                                        .addGroup(imagenfondo2Layout.createSequentialGroup()
                                                .addGroup(imagenfondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(imagenTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(imagenHabitante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(imagenfondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblCantidadhabitante)
                                        .addComponent(lblCantidadtrabajdor))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelImage1.add(imagenfondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 145, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdAsignartrabajadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAsignartrabajadoresActionPerformed
        try {
            AsignarTrabajadores asignar = new AsignarTrabajadores(this.isla, this.barraTrabajadores.getValue(), Integer.parseInt(this.lblCantidadtrabajdor.getText()), this.ciudadjugador, this.recurso);
            asignar.CUAsignarTrabajadores();
        } catch (SQLException ex) {

        }
        this.hide();
    }

    public Isla getIsla() {
        return isla;
    }

    public JSlider getBarraTrabajadores() {
        return barraTrabajadores;
    }//GEN-LAST:event_cmdAsignartrabajadoresActionPerformed

    private void txtCantidadTrabajadoresKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadTrabajadoresKeyReleased

    }//GEN-LAST:event_txtCantidadTrabajadoresKeyReleased

    private void barraTrabajadoresStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_barraTrabajadoresStateChanged
        this.txtCantidadTrabajadores.setText("" + this.barraTrabajadores.getValue());
    }//GEN-LAST:event_barraTrabajadoresStateChanged

    public Ciudad getCiudadjugador() {
        return ciudadjugador;
    }

    public String getRecurso() {
        return recurso;
    }

    public JButton getCmdAsignartrabajadores() {
        return cmdAsignartrabajadores;
    }

    public PanelImage getImagenHabitante() {
        return imagenHabitante;
    }

    public PanelImage getImagenLugar() {
        return imagenLugar;
    }

    public PanelImage getImagenTrabajador() {
        return imagenTrabajador;
    }

    public PanelImage getImagenfondo1() {
        return imagenfondo1;
    }

    public PanelImage getImagenfondo2() {
        return imagenfondo2;
    }

    public JLabel getLblAsignartrabajadores() {
        return lblAsignartrabajadores;
    }

    public JLabel getLblCantidadhabitante() {
        return lblCantidadhabitante;
    }

    public JLabel getLblCantidadtrabajdor() {
        return lblCantidadtrabajdor;
    }

    public PanelImage getPanelImage1() {
        return panelImage1;
    }

    public JTextPane getTxtDescripcionlugarrecurso() {
        return txtDescripcionlugarrecurso;
    }
    // End of variables declaration//GEN-END:variables


}
